export const PARKING_LOT_MODULE = "M103" as const;
export const PARKING_LOT_PERMISSIONS = ["parking_lot.system.configure", "parking_lot.item.create", "parking_lot.request.manage", "parking_lot.context.manage", "parking_lot.revisit.request", "parking_lot.reactivation.request", "parking_lot.disposition.request", "parking_lot.runtime.activate"] as const;
export type ParkingLotPermission = (typeof PARKING_LOT_PERMISSIONS)[number];
export const PARKING_LOT_RUNTIME = { sourceTransfer: false, revisitScheduler: false, eventTriggers: false, contextRefresh: false, searchIndex: false, notifications: false, destinationWrites: false, backgroundJobs: false, analytics: false, providerConnections: false, automation: false } as const;

export type ParkingReasonCategory = "capacity" | "dependency" | "budget" | "compliance" | "risk" | "timing" | "strategic_fit" | "provider" | "evidence" | "superseded" | "other";
export type RevisitTriggerType = "date" | "dependency" | "demand" | "provider" | "regulatory_source" | "capacity" | "budget" | "manual";
export type ParkingDestination = "ideas" | "technical_roadmap" | "business_roadmap" | "future_module" | "research" | "experiment";

export interface ParkingLotSystem { readonly module: typeof PARKING_LOT_MODULE; readonly code: string; readonly status: "draft"; readonly active: false; readonly runtimeEnabled: false; readonly sourceAuthority: false; }
export interface ParkingItem { readonly code: string; readonly systemCode: string; readonly sourceReference: string; readonly version: 1; readonly scope: "local" | "module" | "cross_module" | "platform" | "unknown"; readonly status: "parked_pending_review"; readonly sourceSynchronized: false; readonly reactivated: false; readonly promoted: false; }
export interface ParkingContextSnapshot { readonly code: string; readonly parkingItemCode: string; readonly evidenceReferences: readonly string[]; readonly assumptionReferences: readonly string[]; readonly dependencyReferences: readonly string[]; readonly riskReferences: readonly string[]; readonly status: "draft"; readonly contextRefreshed: false; }
export interface ParkingDecision { readonly code: string; readonly parkingItemCode: string; readonly reason: ParkingReasonCategory; readonly reasonReference: string; readonly status: "review_required"; readonly decisionApplied: false; }
export interface RevisitPolicy { readonly code: string; readonly parkingItemCode: string; readonly triggerTypes: readonly RevisitTriggerType[]; readonly triggerReferences: readonly string[]; readonly status: "draft"; readonly schedulerRegistered: false; readonly notificationScheduled: false; }
export interface ParkingRequest { readonly code: string; readonly sourceReference: string; readonly reasonReference: string; readonly status: "review_required"; readonly targetItemCreated: false; readonly sourceUpdated: false; }
export interface RevisitRequest { readonly code: string; readonly parkingItemCode: string; readonly triggerType: RevisitTriggerType; readonly triggerReference: string; readonly status: "review_required"; readonly contextRefreshStarted: false; readonly reviewStarted: false; }
export interface ReactivationRequest { readonly code: string; readonly parkingItemCode: string; readonly destination: ParkingDestination; readonly destinationReference: string; readonly precheckReferences: readonly string[]; readonly status: "review_required"; readonly destinationWriteExecuted: false; readonly outcomeKnown: false; }
export interface ParkingDispositionRequest { readonly code: string; readonly parkingItemCode: string; readonly action: "repark" | "reject" | "merge" | "supersede"; readonly targetReference: string; readonly status: "review_required"; readonly dispositionApplied: false; }
export interface ParkingReadinessResult { readonly parkingItemCode: string; readonly ready: false; readonly status: "not_ready"; readonly reasons: readonly string[]; }

function permit(value: ParkingLotPermission): void { if (!PARKING_LOT_PERMISSIONS.includes(value)) throw new Error("Unsupported parking lot permission."); }
function code(value: string, field: string): void { if (!/^[A-Z][A-Z0-9_:-]{2,127}$/u.test(value)) throw new Error(`${field} must be a stable safe identifier.`); }
function ref(value: string, field: string): void { if (!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{2,255}$/u.test(value)) throw new Error(`${field} must be a safe reference.`); }
function refs(values: readonly string[], field: string, required = false): readonly string[] { if (required && !values.length) throw new Error(`${field} requires at least one reference.`); for (const value of values) ref(value, field); return [...new Set(values)]; }
function triggers(values: readonly RevisitTriggerType[]): readonly RevisitTriggerType[] { if (!values.length) throw new Error("Revisit policies require trigger types."); return [...new Set(values)]; }

export function createParkingLotSystem(input: { permission: ParkingLotPermission; code: string }): ParkingLotSystem { permit(input.permission); code(input.code, "Parking lot system code"); return { module: PARKING_LOT_MODULE, code: input.code, status: "draft", active: false, runtimeEnabled: false, sourceAuthority: false }; }
export function createParkingItem(input: { permission: ParkingLotPermission; code: string; system: ParkingLotSystem; sourceReference: string; scope: ParkingItem["scope"] }): ParkingItem { permit(input.permission); code(input.code, "Parking item code"); ref(input.sourceReference, "Parking source reference"); return { code: input.code, systemCode: input.system.code, sourceReference: input.sourceReference, version: 1, scope: input.scope, status: "parked_pending_review", sourceSynchronized: false, reactivated: false, promoted: false }; }
export function createParkingContextSnapshot(input: { permission: ParkingLotPermission; code: string; item: ParkingItem; evidenceReferences?: readonly string[]; assumptionReferences?: readonly string[]; dependencyReferences?: readonly string[]; riskReferences?: readonly string[] }): ParkingContextSnapshot { permit(input.permission); code(input.code, "Parking context snapshot code"); return { code: input.code, parkingItemCode: input.item.code, evidenceReferences: refs(input.evidenceReferences ?? [], "Evidence references"), assumptionReferences: refs(input.assumptionReferences ?? [], "Assumption references"), dependencyReferences: refs(input.dependencyReferences ?? [], "Dependency references"), riskReferences: refs(input.riskReferences ?? [], "Risk references"), status: "draft", contextRefreshed: false }; }
export function recordParkingDecision(input: { permission: ParkingLotPermission; code: string; item: ParkingItem; reason: ParkingReasonCategory; reasonReference: string }): ParkingDecision { permit(input.permission); code(input.code, "Parking decision code"); ref(input.reasonReference, "Parking reason reference"); return { code: input.code, parkingItemCode: input.item.code, reason: input.reason, reasonReference: input.reasonReference, status: "review_required", decisionApplied: false }; }
export function defineRevisitPolicy(input: { permission: ParkingLotPermission; code: string; item: ParkingItem; triggerTypes: readonly RevisitTriggerType[]; triggerReferences: readonly string[] }): RevisitPolicy { permit(input.permission); code(input.code, "Revisit policy code"); return { code: input.code, parkingItemCode: input.item.code, triggerTypes: triggers(input.triggerTypes), triggerReferences: refs(input.triggerReferences, "Revisit trigger references", true), status: "draft", schedulerRegistered: false, notificationScheduled: false }; }
export function requestParking(input: { permission: ParkingLotPermission; code: string; sourceReference: string; reasonReference: string }): ParkingRequest { permit(input.permission); code(input.code, "Parking request code"); ref(input.sourceReference, "Parking request source reference"); ref(input.reasonReference, "Parking request reason reference"); return { code: input.code, sourceReference: input.sourceReference, reasonReference: input.reasonReference, status: "review_required", targetItemCreated: false, sourceUpdated: false }; }
export function requestRevisit(input: { permission: ParkingLotPermission; code: string; item: ParkingItem; triggerType: RevisitTriggerType; triggerReference: string }): RevisitRequest { permit(input.permission); code(input.code, "Revisit request code"); ref(input.triggerReference, "Revisit trigger reference"); return { code: input.code, parkingItemCode: input.item.code, triggerType: input.triggerType, triggerReference: input.triggerReference, status: "review_required", contextRefreshStarted: false, reviewStarted: false }; }
export function requestReactivation(input: { permission: ParkingLotPermission; code: string; item: ParkingItem; destination: ParkingDestination; destinationReference: string; precheckReferences: readonly string[] }): ReactivationRequest { permit(input.permission); code(input.code, "Reactivation request code"); ref(input.destinationReference, "Reactivation destination reference"); return { code: input.code, parkingItemCode: input.item.code, destination: input.destination, destinationReference: input.destinationReference, precheckReferences: refs(input.precheckReferences, "Reactivation prechecks", true), status: "review_required", destinationWriteExecuted: false, outcomeKnown: false }; }
export function requestParkingDisposition(input: { permission: ParkingLotPermission; code: string; item: ParkingItem; action: ParkingDispositionRequest["action"]; targetReference: string }): ParkingDispositionRequest { permit(input.permission); code(input.code, "Parking disposition request code"); ref(input.targetReference, "Disposition target reference"); return { code: input.code, parkingItemCode: input.item.code, action: input.action, targetReference: input.targetReference, status: "review_required", dispositionApplied: false }; }
export function evaluateParkingReadiness(input: { item: ParkingItem; decision: ParkingDecision }): ParkingReadinessResult { const reasons=["parking_runtime_disabled", "human_approval_required", "context_not_preserved_or_refreshed", "triggers_not_evaluated", "destination_not_authorized"]; if(input.item.code!==input.decision.parkingItemCode) reasons.push("decision_item_mismatch"); return { parkingItemCode: input.item.code, ready: false, status: "not_ready", reasons }; }