CREATE OR REPLACE FUNCTION atlas_auth_current_account_id() RETURNS text LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('atlas.auth_account_id', true), '') $$;--> statement-breakpoint
REVOKE ALL ON FUNCTION atlas_auth_current_account_id() FROM PUBLIC;--> statement-breakpoint
DROP POLICY IF EXISTS "auth_external_identities_auth_gateway_only" ON auth_external_identities; CREATE POLICY "auth_external_identities_auth_gateway_only" ON auth_external_identities FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_sessions_auth_gateway_only" ON auth_sessions; CREATE POLICY "auth_sessions_auth_gateway_only" ON auth_sessions FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_provider_vault_auth_gateway_only" ON auth_provider_vault; CREATE POLICY "auth_provider_vault_auth_gateway_only" ON auth_provider_vault FOR ALL TO atlas_auth_gateway USING (EXISTS (SELECT 1 FROM auth_sessions s WHERE s.id = session_id AND s.account_id = atlas_auth_current_account_id())) WITH CHECK (EXISTS (SELECT 1 FROM auth_sessions s WHERE s.id = session_id AND s.account_id = atlas_auth_current_account_id()));--> statement-breakpoint
DROP POLICY IF EXISTS "auth_proofs_auth_gateway_only" ON auth_proofs; CREATE POLICY "auth_proofs_auth_gateway_only" ON auth_proofs FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_invitations_auth_gateway_only" ON auth_invitations; CREATE POLICY "auth_invitations_auth_gateway_only" ON auth_invitations FOR ALL TO atlas_auth_gateway USING (EXISTS (SELECT 1 FROM auth_proofs p WHERE p.id = proof_id AND p.account_id = atlas_auth_current_account_id())) WITH CHECK (EXISTS (SELECT 1 FROM auth_proofs p WHERE p.id = proof_id AND p.account_id = atlas_auth_current_account_id()));--> statement-breakpoint
DROP POLICY IF EXISTS "auth_party_links_auth_gateway_only" ON auth_party_links; CREATE POLICY "auth_party_links_auth_gateway_only" ON auth_party_links FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_role_assignments_auth_gateway_only" ON auth_role_assignments; CREATE POLICY "auth_role_assignments_auth_gateway_only" ON auth_role_assignments FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_mfa_factors_auth_gateway_only" ON auth_mfa_factors; CREATE POLICY "auth_mfa_factors_auth_gateway_only" ON auth_mfa_factors FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_security_events_auth_gateway_only" ON auth_security_events; CREATE POLICY "auth_security_events_auth_gateway_only" ON auth_security_events FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
DROP POLICY IF EXISTS "auth_outbox_auth_gateway_only" ON auth_outbox; CREATE POLICY "auth_outbox_auth_gateway_only" ON auth_outbox FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());--> statement-breakpoint
REVOKE ALL ON auth_organizations, auth_roles, auth_role_permissions, auth_service_accounts, auth_rate_buckets, auth_transactions FROM atlas_auth_gateway;
