-- M007: forward-only completion of the context-bound RLS boundary.
ALTER TABLE auth_accounts, auth_external_identities, auth_sessions, auth_provider_vault, auth_transactions, auth_proofs, auth_invitations, auth_party_links, auth_organizations, auth_roles, auth_role_permissions, auth_role_assignments, auth_mfa_factors, auth_service_accounts, auth_rate_buckets, auth_security_events, auth_outbox ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE auth_accounts, auth_external_identities, auth_sessions, auth_provider_vault, auth_transactions, auth_proofs, auth_invitations, auth_party_links, auth_organizations, auth_roles, auth_role_permissions, auth_role_assignments, auth_mfa_factors, auth_service_accounts, auth_rate_buckets, auth_security_events, auth_outbox FORCE ROW LEVEL SECURITY;--> statement-breakpoint
REVOKE ALL ON auth_accounts, auth_external_identities, auth_sessions, auth_provider_vault, auth_transactions, auth_proofs, auth_invitations, auth_party_links, auth_organizations, auth_roles, auth_role_permissions, auth_role_assignments, auth_mfa_factors, auth_service_accounts, auth_rate_buckets, auth_security_events, auth_outbox FROM PUBLIC;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON auth_accounts, auth_external_identities, auth_sessions, auth_provider_vault, auth_transactions, auth_proofs, auth_invitations, auth_party_links, auth_organizations, auth_roles, auth_role_permissions, auth_role_assignments, auth_mfa_factors, auth_service_accounts, auth_rate_buckets, auth_security_events, auth_outbox TO atlas_auth_gateway;--> statement-breakpoint
DROP POLICY IF EXISTS "auth_transactions_context_required" ON auth_transactions; CREATE POLICY "auth_transactions_context_required" ON auth_transactions FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
DROP POLICY IF EXISTS "auth_organizations_context_required" ON auth_organizations; CREATE POLICY "auth_organizations_context_required" ON auth_organizations FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
DROP POLICY IF EXISTS "auth_roles_context_required" ON auth_roles; CREATE POLICY "auth_roles_context_required" ON auth_roles FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
DROP POLICY IF EXISTS "auth_role_permissions_context_required" ON auth_role_permissions; CREATE POLICY "auth_role_permissions_context_required" ON auth_role_permissions FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
DROP POLICY IF EXISTS "auth_service_accounts_context_required" ON auth_service_accounts; CREATE POLICY "auth_service_accounts_context_required" ON auth_service_accounts FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
DROP POLICY IF EXISTS "auth_rate_buckets_context_required" ON auth_rate_buckets; CREATE POLICY "auth_rate_buckets_context_required" ON auth_rate_buckets FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
