-- M007: immutable server-issued identity evidence and durable manual-review conflicts.
CREATE TABLE auth_supabase_identity_evidence (id text PRIMARY KEY, provider varchar(32) NOT NULL CHECK (provider = 'google'), provider_subject text NOT NULL, issuer text NOT NULL, audience text NOT NULL, email_verified boolean NOT NULL, provider_transaction_id text NOT NULL UNIQUE, verified_at timestamptz NOT NULL, expires_at timestamptz NOT NULL CHECK (expires_at > verified_at), created_at timestamptz NOT NULL);--> statement-breakpoint
CREATE INDEX auth_supabase_identity_evidence_subject_idx ON auth_supabase_identity_evidence (provider, provider_subject);--> statement-breakpoint
CREATE TABLE auth_crm_party_evidence (id text PRIMARY KEY, supabase_evidence_id text NOT NULL REFERENCES auth_supabase_identity_evidence(id) ON DELETE RESTRICT, party_id text, resolution varchar(24) NOT NULL CHECK (resolution IN ('linked','possible_match','conflict','unavailable')), relationship_receipt text, verified_at timestamptz NOT NULL, expires_at timestamptz NOT NULL CHECK (expires_at > verified_at), created_at timestamptz NOT NULL, CONSTRAINT auth_crm_party_evidence_link_receipt CHECK (resolution <> 'linked' OR relationship_receipt IS NOT NULL));--> statement-breakpoint
CREATE INDEX auth_crm_party_evidence_identity_idx ON auth_crm_party_evidence (supabase_evidence_id, verified_at);--> statement-breakpoint
CREATE TABLE auth_identity_conflicts (id text PRIMARY KEY, account_id text NOT NULL REFERENCES auth_accounts(id) ON DELETE CASCADE, external_identity_id text NOT NULL REFERENCES auth_external_identities(id) ON DELETE CASCADE, supabase_evidence_id text NOT NULL REFERENCES auth_supabase_identity_evidence(id) ON DELETE RESTRICT, crm_evidence_id text NOT NULL REFERENCES auth_crm_party_evidence(id) ON DELETE RESTRICT, reason varchar(32) NOT NULL, state varchar(24) NOT NULL CHECK (state IN ('manual_review','resolved')), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);--> statement-breakpoint
CREATE INDEX auth_identity_conflicts_account_state_idx ON auth_identity_conflicts (account_id, state);--> statement-breakpoint
ALTER TABLE auth_supabase_identity_evidence, auth_crm_party_evidence, auth_identity_conflicts ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE auth_supabase_identity_evidence, auth_crm_party_evidence, auth_identity_conflicts FORCE ROW LEVEL SECURITY;--> statement-breakpoint
REVOKE ALL ON auth_supabase_identity_evidence, auth_crm_party_evidence, auth_identity_conflicts FROM PUBLIC;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON auth_supabase_identity_evidence, auth_crm_party_evidence, auth_identity_conflicts TO atlas_auth_gateway;--> statement-breakpoint
CREATE POLICY auth_supabase_identity_evidence_auth_gateway_only ON auth_supabase_identity_evidence FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
CREATE POLICY auth_crm_party_evidence_auth_gateway_only ON auth_crm_party_evidence FOR ALL TO atlas_auth_gateway USING (current_setting('atlas.auth_context_verified', true) = '1') WITH CHECK (current_setting('atlas.auth_context_verified', true) = '1');--> statement-breakpoint
CREATE POLICY auth_identity_conflicts_auth_gateway_only ON auth_identity_conflicts FOR ALL TO atlas_auth_gateway USING (account_id = atlas_auth_current_account_id()) WITH CHECK (account_id = atlas_auth_current_account_id());
