-- AR-007: atomic multi-risk admission, append-only audit identity, and owner-reconciled outbox leases.
CREATE OR REPLACE FUNCTION atlas_auth_admit_risk_keys(p_action text, p_keys text[], p_threshold integer, p_window_seconds integer, p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$ DECLARE risk_key text; bucket_count integer; allowed boolean := true; BEGIN IF p_action !~ '^[a-z_]{3,64}$' OR cardinality(p_keys) <> 5 OR p_threshold < 1 OR p_window_seconds < 1 THEN RAISE EXCEPTION 'auth_rate_input_denied'; END IF; FOREACH risk_key IN ARRAY p_keys LOOP IF length(risk_key) < 16 THEN RAISE EXCEPTION 'auth_rate_key_denied'; END IF; INSERT INTO public.auth_rate_buckets (bucket_digest, purpose, count, window_started_at, expires_at, updated_at) VALUES (risk_key,p_action,1,p_now,p_now + make_interval(secs => p_window_seconds),p_now) ON CONFLICT (bucket_digest) DO UPDATE SET count = CASE WHEN auth_rate_buckets.expires_at <= excluded.window_started_at THEN 1 ELSE auth_rate_buckets.count + 1 END, window_started_at = CASE WHEN auth_rate_buckets.expires_at <= excluded.window_started_at THEN excluded.window_started_at ELSE auth_rate_buckets.window_started_at END, expires_at = CASE WHEN auth_rate_buckets.expires_at <= excluded.window_started_at THEN excluded.expires_at ELSE auth_rate_buckets.expires_at END, updated_at = excluded.updated_at RETURNING count INTO bucket_count; IF bucket_count > p_threshold THEN allowed := false; END IF; END LOOP; RETURN allowed; END; $$;--> statement-breakpoint
REVOKE ALL ON FUNCTION atlas_auth_admit_risk_keys(text,text[],integer,integer,timestamptz) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_admit_risk_keys(text,text[],integer,integer,timestamptz) TO atlas_auth_preauth, atlas_auth_gateway;--> statement-breakpoint
CREATE SEQUENCE auth_security_event_sequence;--> statement-breakpoint
SELECT setval('auth_security_event_sequence', GREATEST(COALESCE((SELECT max(sequence) FROM auth_security_events),0) + 1,1), false);--> statement-breakpoint
ALTER SEQUENCE auth_security_event_sequence OWNED BY auth_security_events.sequence;--> statement-breakpoint
ALTER TABLE auth_security_events ALTER COLUMN sequence SET DEFAULT nextval('auth_security_event_sequence');--> statement-breakpoint
ALTER TABLE auth_security_events ADD COLUMN event_key text;--> statement-breakpoint
UPDATE auth_security_events SET event_key=id WHERE event_key IS NULL;--> statement-breakpoint
ALTER TABLE auth_security_events ALTER COLUMN event_key SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX auth_security_events_event_key_unique ON auth_security_events(event_key);--> statement-breakpoint
ALTER TABLE auth_security_events ADD COLUMN metadata jsonb NOT NULL DEFAULT '{}'::jsonb;--> statement-breakpoint
ALTER TABLE auth_outbox ADD COLUMN channel varchar(24);--> statement-breakpoint
ALTER TABLE auth_outbox ADD COLUMN lease_purpose varchar(16);--> statement-breakpoint
ALTER TABLE auth_outbox ADD COLUMN provider_outcome varchar(16);--> statement-breakpoint
ALTER TABLE auth_outbox ADD COLUMN provider_message_id text;--> statement-breakpoint
ALTER TABLE auth_outbox ADD COLUMN reconcile_after timestamptz;--> statement-breakpoint
ALTER TABLE auth_outbox DROP CONSTRAINT auth_outbox_state_valid;--> statement-breakpoint
ALTER TABLE auth_outbox ADD CONSTRAINT auth_outbox_state_valid CHECK (state IN ('pending','leased','reconciling','completed','manual_review'));--> statement-breakpoint
ALTER TABLE auth_outbox ADD CONSTRAINT auth_outbox_channel_valid CHECK (channel IS NULL OR channel IN ('email','otp','security_alert','invitation'));--> statement-breakpoint
ALTER TABLE auth_outbox ADD CONSTRAINT auth_outbox_lease_purpose_valid CHECK (lease_purpose IS NULL OR lease_purpose IN ('dispatch','reconcile'));--> statement-breakpoint
ALTER TABLE auth_outbox ADD CONSTRAINT auth_outbox_provider_outcome_valid CHECK (provider_outcome IS NULL OR provider_outcome IN ('sent','failed','unknown'));--> statement-breakpoint
CREATE INDEX auth_outbox_lease_idx ON auth_outbox(state, lease_purpose, lease_expires_at);--> statement-breakpoint
CREATE INDEX auth_outbox_reconcile_idx ON auth_outbox(state, provider_outcome, reconcile_after);--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_admit_pre_auth(p_bucket text, p_purpose text, p_command text, p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$ DECLARE bucket_count integer; BEGIN IF length(p_bucket) < 32 OR p_purpose !~ '^[a-z_]{3,64}$' OR length(p_command) < 16 THEN RAISE EXCEPTION 'auth_preauth_input_denied'; END IF; INSERT INTO public.auth_rate_buckets (bucket_digest, purpose, count, window_started_at, expires_at, updated_at) VALUES (p_bucket,p_purpose,1,p_now,p_now + interval '1 minute',p_now) ON CONFLICT (bucket_digest) DO UPDATE SET count = CASE WHEN auth_rate_buckets.expires_at <= excluded.window_started_at THEN 1 ELSE auth_rate_buckets.count + 1 END, window_started_at = CASE WHEN auth_rate_buckets.expires_at <= excluded.window_started_at THEN excluded.window_started_at ELSE auth_rate_buckets.window_started_at END, expires_at = CASE WHEN auth_rate_buckets.expires_at <= excluded.window_started_at THEN excluded.expires_at ELSE auth_rate_buckets.expires_at END, updated_at = excluded.updated_at RETURNING count INTO bucket_count; IF bucket_count > 10 THEN RETURN false; END IF; INSERT INTO public.auth_security_events (id,event_key,account_id,sequence,event_name,outcome,correlation_id,policy_version,metadata,occurred_at) VALUES (p_command || ':audit',p_command || ':audit',NULL,1,p_purpose,'accepted',p_command,1,'{}'::jsonb,p_now) ON CONFLICT (id) DO NOTHING; INSERT INTO public.auth_outbox (command_id,account_id,purpose,idempotency_key,state,attempt_count,lease_version,available_at,payload,created_at,updated_at) VALUES (p_command,NULL,p_purpose,p_command,'pending',0,0,p_now,'{}'::jsonb,p_now,p_now) ON CONFLICT (command_id) DO NOTHING; RETURN true; END; $$;
