-- M007 final trust boundaries: no pre-auth, gateway, or worker table DML.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='atlas_auth_worker') THEN CREATE ROLE atlas_auth_worker NOLOGIN; END IF; END $$;--> statement-breakpoint
REVOKE ALL ON auth_transactions, auth_supabase_identity_evidence, auth_crm_party_evidence, auth_identity_conflicts, auth_durable_invitations, auth_rate_buckets, auth_security_events, auth_outbox FROM atlas_auth_gateway, atlas_auth_preauth, atlas_auth_worker;--> statement-breakpoint
ALTER TABLE auth_transactions ADD COLUMN redirect_hash text;--> statement-breakpoint
ALTER TABLE auth_durable_invitations ADD COLUMN expected_provider_subject text;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_issue_oauth_transaction(p_id text,p_purpose text,p_provider text,p_state text,p_nonce text,p_pkce text,p_browser text,p_redirect text,p_return text,p_callback text,p_expires timestamptz,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN
  IF length(p_id)<16 OR p_purpose NOT IN ('sign_in','link') OR p_provider<>'google' OR length(p_state)<32 OR length(p_nonce)<32 OR length(p_pkce)<32 OR length(p_browser)<32 OR p_return !~ '^/(?!/)' OR p_callback !~ '^https://[^/?#]+/api/auth/oauth/google/callback$' OR p_expires<=p_now OR p_expires>p_now+interval '15 minutes' THEN RAISE EXCEPTION 'auth_oauth_input_denied'; END IF;
  IF length(p_redirect)<32 THEN RAISE EXCEPTION 'auth_oauth_redirect_denied'; END IF;
  INSERT INTO public.auth_transactions(id,purpose,provider,state_digest,nonce_digest,pkce_verifier_digest,browser_binding_digest,redirect_hash,return_intent,callback_url,state,expires_at,version,created_at,updated_at) VALUES(p_id,p_purpose,p_provider,p_state,p_nonce,p_pkce,p_browser,p_redirect,p_return,p_callback,'pending',p_expires,1,p_now,p_now);
END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_consume_oauth_transaction(p_state text,p_nonce text,p_pkce text,p_browser text,p_redirect text,p_now timestamptz) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE v_id text; BEGIN
  IF length(p_state)<32 OR length(p_nonce)<32 OR length(p_pkce)<32 OR length(p_browser)<32 OR length(p_redirect)<32 THEN RAISE EXCEPTION 'auth_oauth_input_denied'; END IF;
  UPDATE public.auth_transactions SET state='consumed',consumed_at=p_now,updated_at=p_now,version=version+1 WHERE state='pending' AND expires_at>p_now AND state_digest=p_state AND nonce_digest=p_nonce AND pkce_verifier_digest=p_pkce AND browser_binding_digest=p_browser AND redirect_hash=p_redirect RETURNING id INTO v_id;
  RETURN CASE WHEN v_id IS NULL THEN 'replay_denied' ELSE 'consumed' END;
END $$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_store_supabase_evidence(p_id text,p_provider text,p_subject text,p_issuer text,p_audience text,p_verified boolean,p_transaction text,p_verified_at timestamptz,p_expires timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN
  IF length(p_id)<16 OR p_provider<>'google' OR length(p_subject)<1 OR length(p_issuer)<8 OR length(p_audience)<1 OR p_verified IS DISTINCT FROM true OR length(p_transaction)<16 OR p_expires<=p_verified_at THEN RAISE EXCEPTION 'auth_identity_evidence_denied'; END IF;
  INSERT INTO public.auth_supabase_identity_evidence(id,provider,provider_subject,issuer,audience,email_verified,provider_transaction_id,verified_at,expires_at,created_at) VALUES(p_id,p_provider,p_subject,p_issuer,p_audience,true,p_transaction,p_verified_at,p_expires,p_verified_at);
END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_store_crm_evidence(p_id text,p_evidence text,p_party text,p_resolution text,p_receipt text,p_verified_at timestamptz,p_expires timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN
  IF length(p_id)<16 OR length(p_evidence)<16 OR p_resolution NOT IN ('linked','possible_match','conflict','unavailable') OR (p_resolution='linked' AND (coalesce(length(p_party),0)<1 OR coalesce(length(p_receipt),0)<16)) OR p_expires<=p_verified_at THEN RAISE EXCEPTION 'auth_crm_evidence_denied'; END IF;
  INSERT INTO public.auth_crm_party_evidence(id,supabase_evidence_id,party_id,resolution,relationship_receipt,verified_at,expires_at,created_at) VALUES(p_id,p_evidence,p_party,p_resolution,p_receipt,p_verified_at,p_expires,p_verified_at);
END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_authenticate_identity(p_evidence text,p_crm text,p_issuer text,p_audience text,p_new_account text,p_external text,p_party_link text,p_conflict text,p_session text,p_handle text,p_family text,p_assurance text,p_idle timestamptz,p_absolute timestamptz,p_now timestamptz) RETURNS TABLE(kind text,account_id text) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE v_subject text; v_resolution text; v_receipt text; v_account text; v_external text; v_external_account text; BEGIN
  IF length(p_handle)<32 OR p_assurance<>'aal1' OR p_idle<=p_now OR p_absolute<=p_idle THEN RAISE EXCEPTION 'auth_session_input_denied'; END IF;
  SELECT provider_subject INTO v_subject FROM public.auth_supabase_identity_evidence WHERE id=p_evidence AND provider='google' AND issuer=p_issuer AND audience=p_audience AND email_verified=true AND verified_at<=p_now AND expires_at>p_now;
  IF v_subject IS NULL THEN RETURN QUERY SELECT 'denied'::text,NULL::text; RETURN; END IF;
  SELECT resolution,relationship_receipt INTO v_resolution,v_receipt FROM public.auth_crm_party_evidence WHERE id=p_crm AND supabase_evidence_id=p_evidence AND verified_at<=p_now AND expires_at>p_now;
  IF v_resolution IS NULL THEN RETURN QUERY SELECT 'denied'::text,NULL::text; RETURN; END IF;
  INSERT INTO public.auth_accounts(id,supabase_subject,status,authentication_epoch,access_epoch,policy_epoch,version,created_at,updated_at) VALUES(p_new_account,v_subject,CASE WHEN v_resolution='linked' THEN 'active' ELSE 'limited' END,1,1,1,1,p_now,p_now) ON CONFLICT(supabase_subject) DO UPDATE SET updated_at=excluded.updated_at RETURNING id INTO v_account;
  INSERT INTO public.auth_external_identities(id,account_id,provider,provider_subject,state,linked_at,version,created_at,updated_at) VALUES(p_external,v_account,'google',v_subject,'active',p_now,1,p_now,p_now) ON CONFLICT(provider,provider_subject) DO UPDATE SET updated_at=excluded.updated_at RETURNING id,auth_external_identities.account_id INTO v_external,v_external_account;
  IF v_resolution<>'linked' OR v_receipt IS NULL OR v_external_account<>v_account THEN INSERT INTO public.auth_identity_conflicts(id,account_id,external_identity_id,supabase_evidence_id,crm_evidence_id,reason,state,created_at,updated_at) VALUES(p_conflict,v_account,v_external,p_evidence,p_crm,coalesce(v_resolution,'conflict'),'manual_review',p_now,p_now) ON CONFLICT(id) DO NOTHING; RETURN QUERY SELECT 'manual_review'::text,v_account; RETURN; END IF;
  INSERT INTO public.auth_party_links(id,account_id,relationship_receipt,state,access_version,created_at,updated_at) VALUES(p_party_link,v_account,v_receipt,'active',1,p_now,p_now) ON CONFLICT(relationship_receipt) DO UPDATE SET updated_at=excluded.updated_at;
  INSERT INTO public.auth_sessions(id,account_id,handle_digest,family_id,generation,assurance,state,idle_expires_at,absolute_expires_at,version,created_at,updated_at) VALUES(p_session,v_account,p_handle,p_family,1,p_assurance,'active',p_idle,p_absolute,1,p_now,p_now);
  RETURN QUERY SELECT 'authenticated'::text,v_account;
END $$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_issue_invitation(p_id text,p_proof text,p_contact text,p_scope text,p_inviter text,p_subject text,p_expires timestamptz,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN
  IF length(p_id)<16 OR length(p_proof)<32 OR length(p_contact)<1 OR p_scope !~ '^[a-z_]{3,64}$' OR length(p_subject)<1 OR p_expires<=p_now OR p_expires>p_now+interval '1 day' OR NOT EXISTS(SELECT 1 FROM public.auth_accounts WHERE id=p_inviter AND status='active') THEN RAISE EXCEPTION 'auth_invitation_input_denied'; END IF;
  INSERT INTO public.auth_durable_invitations(id,proof_digest,contact_id,scope,inviter_account_id,expected_provider_subject,state,expires_at,created_at,updated_at) VALUES(p_id,p_proof,p_contact,p_scope,p_inviter,p_subject,'issued',p_expires,p_now,p_now);
END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_consume_invitation(p_id text,p_proof text,p_session_handle text,p_now timestamptz) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE v_expected text; v_subject text; v_evidence text; BEGIN
  SELECT expected_provider_subject INTO v_expected FROM public.auth_durable_invitations WHERE id=p_id AND proof_digest=p_proof AND state='issued' AND expires_at>p_now FOR UPDATE;
  IF v_expected IS NULL THEN RETURN 'manual_review'; END IF;
  SELECT identity.provider_subject INTO v_subject FROM public.auth_sessions session JOIN public.auth_external_identities identity ON identity.account_id=session.account_id AND identity.provider='google' AND identity.state='active' WHERE session.handle_digest=p_session_handle AND session.state='active' AND session.idle_expires_at>p_now AND session.absolute_expires_at>p_now;
  SELECT id INTO v_evidence FROM public.auth_supabase_identity_evidence WHERE provider='google' AND provider_subject=v_subject AND email_verified=true AND verified_at<=p_now AND expires_at>p_now ORDER BY verified_at DESC LIMIT 1;
  IF v_subject IS NULL OR v_evidence IS NULL OR v_subject<>v_expected THEN UPDATE public.auth_durable_invitations SET state='manual_review',updated_at=p_now WHERE id=p_id AND state='issued'; RETURN 'manual_review'; END IF;
  UPDATE public.auth_durable_invitations SET state='accepted',identity_evidence_id=v_evidence,accepted_at=p_now,updated_at=p_now WHERE id=p_id AND state='issued'; RETURN 'consumed';
END $$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_create_session(p_id text,p_account text,p_handle text,p_family text,p_assurance text,p_idle timestamptz,p_absolute timestamptz,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN IF length(p_handle)<32 OR p_assurance NOT IN ('aal1','aal2') OR p_idle<=p_now OR p_absolute<=p_idle OR NOT EXISTS(SELECT 1 FROM public.auth_accounts WHERE id=p_account AND status IN ('active','limited')) THEN RAISE EXCEPTION 'auth_session_input_denied'; END IF; INSERT INTO public.auth_sessions(id,account_id,handle_digest,family_id,generation,assurance,state,idle_expires_at,absolute_expires_at,version,created_at,updated_at) VALUES(p_id,p_account,p_handle,p_family,1,p_assurance,'active',p_idle,p_absolute,1,p_now,p_now); END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_list_sessions(p_handle text,p_now timestamptz) RETURNS TABLE(id text,created_at timestamptz,is_current boolean) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ SELECT candidate.id,candidate.created_at,candidate.handle_digest=p_handle FROM public.auth_sessions current_session JOIN public.auth_sessions candidate ON candidate.account_id=current_session.account_id WHERE current_session.handle_digest=p_handle AND current_session.state='active' AND current_session.idle_expires_at>p_now AND current_session.absolute_expires_at>p_now AND candidate.state='active' AND candidate.idle_expires_at>p_now AND candidate.absolute_expires_at>p_now ORDER BY candidate.created_at DESC $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_rotate_session(p_handle text,p_next_id text,p_next_handle text,p_idle timestamptz,p_absolute timestamptz,p_now timestamptz) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE current_row public.auth_sessions%ROWTYPE; BEGIN SELECT * INTO current_row FROM public.auth_sessions WHERE handle_digest=p_handle FOR UPDATE; IF current_row.id IS NULL OR current_row.state<>'active' OR current_row.idle_expires_at<=p_now OR current_row.absolute_expires_at<=p_now THEN IF current_row.id IS NOT NULL THEN UPDATE public.auth_sessions SET state='revoked',revoked_at=p_now,updated_at=p_now WHERE family_id=current_row.family_id AND state IN ('active','rotating'); END IF; RETURN 'family_revoked'; END IF; UPDATE public.auth_sessions SET state='rotated',updated_at=p_now,version=version+1 WHERE id=current_row.id AND state='active'; INSERT INTO public.auth_sessions(id,account_id,handle_digest,family_id,generation,assurance,state,idle_expires_at,absolute_expires_at,version,created_at,updated_at) VALUES(p_next_id,current_row.account_id,p_next_handle,current_row.family_id,current_row.generation+1,current_row.assurance,'active',p_idle,p_absolute,1,p_now,p_now); RETURN 'rotated'; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_revoke_current(p_handle text,p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE changed integer; BEGIN UPDATE public.auth_sessions SET state='revoked',revoked_at=p_now,updated_at=p_now,version=version+1 WHERE handle_digest=p_handle AND state IN ('active','rotating'); GET DIAGNOSTICS changed=ROW_COUNT; RETURN changed=1; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_revoke_others(p_handle text,p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE current_id text; current_account text; BEGIN SELECT id,account_id INTO current_id,current_account FROM public.auth_sessions WHERE handle_digest=p_handle AND state='active' AND idle_expires_at>p_now AND absolute_expires_at>p_now FOR UPDATE; IF current_id IS NULL THEN RETURN false; END IF; UPDATE public.auth_sessions SET state='revoked',revoked_at=p_now,updated_at=p_now,version=version+1 WHERE account_id=current_account AND id<>current_id AND state IN ('active','rotating'); RETURN true; END $$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_append_audit(p_event text,p_name text,p_outcome text,p_correlation text,p_account text,p_metadata jsonb,p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE v_id text; BEGIN IF length(p_event)<16 OR p_name !~ '^[a-z_]{3,80}$' OR length(p_outcome)<1 OR length(p_correlation)<8 OR jsonb_typeof(p_metadata)<>'object' OR EXISTS(SELECT 1 FROM jsonb_object_keys(p_metadata) key WHERE key NOT IN ('outcome','riskClass','provider','channel','reasonCode','policyVersion')) THEN RAISE EXCEPTION 'auth_audit_input_denied'; END IF; INSERT INTO public.auth_security_events(id,event_key,account_id,event_name,outcome,correlation_id,policy_version,metadata,occurred_at) VALUES(p_event,p_event,p_account,p_name,p_outcome,p_correlation,1,p_metadata,p_now) ON CONFLICT(event_key) DO NOTHING RETURNING id INTO v_id; RETURN v_id IS NOT NULL; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_admit_and_enqueue(p_action text,p_keys text[],p_threshold integer,p_window integer,p_event text,p_correlation text,p_account text,p_metadata jsonb,p_command text,p_purpose text,p_channel text,p_idempotency text,p_payload jsonb,p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE v_allowed boolean; BEGIN IF cardinality(p_keys)<1 OR cardinality(p_keys)>5 THEN RAISE EXCEPTION 'auth_rate_input_denied'; END IF; SELECT public.atlas_auth_admit_risk_keys(p_action,p_keys,p_threshold,p_window,p_now) INTO v_allowed; PERFORM public.atlas_auth_append_audit(p_event,p_action||'_admission',CASE WHEN v_allowed THEN 'accepted' ELSE 'rate_limited' END,p_correlation,p_account,p_metadata||jsonb_build_object('outcome',CASE WHEN v_allowed THEN 'accepted' ELSE 'rate_limited' END),p_now); IF v_allowed AND p_command IS NOT NULL THEN IF length(p_command)<16 OR p_purpose !~ '^[a-z_]{3,64}$' OR p_channel NOT IN ('email','otp','security_alert','invitation') OR length(p_idempotency)<8 OR jsonb_typeof(p_payload)<>'object' THEN RAISE EXCEPTION 'auth_outbox_input_denied'; END IF; INSERT INTO public.auth_outbox(command_id,account_id,purpose,channel,idempotency_key,state,attempt_count,lease_version,available_at,payload,created_at,updated_at) VALUES(p_command,p_account,p_purpose,p_channel,p_idempotency,'pending',0,0,p_now,p_payload,p_now,p_now) ON CONFLICT(idempotency_key) DO NOTHING; END IF; RETURN v_allowed; END $$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_recover_outbox_leases(p_now timestamptz) RETURNS TABLE(dispatch_to_reconcile integer,reconcile_to_manual_review integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE d integer; r integer; BEGIN UPDATE public.auth_outbox SET state='reconciling',provider_outcome='unknown',lease_owner=NULL,lease_purpose=NULL,lease_expires_at=NULL,reconcile_after=p_now,updated_at=p_now WHERE state='leased' AND lease_purpose='dispatch' AND lease_expires_at<=p_now; GET DIAGNOSTICS d=ROW_COUNT; UPDATE public.auth_outbox SET state='manual_review',provider_outcome='unknown',result_code='reconcile_lease_expired',lease_owner=NULL,lease_purpose=NULL,lease_expires_at=NULL,updated_at=p_now WHERE state='leased' AND lease_purpose='reconcile' AND lease_expires_at<=p_now; GET DIAGNOSTICS r=ROW_COUNT; RETURN QUERY SELECT d,r; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_lease_outbox(p_owner text,p_lease_purpose text,p_limit integer,p_now timestamptz,p_expires timestamptz) RETURNS TABLE(command_id text,purpose text,channel varchar,idempotency_key varchar,payload jsonb,attempt_count integer,lease_version integer) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN IF length(p_owner)<8 OR p_lease_purpose NOT IN ('dispatch','reconcile') OR p_limit<1 OR p_limit>100 OR p_expires<=p_now THEN RAISE EXCEPTION 'auth_outbox_lease_denied'; END IF; RETURN QUERY WITH candidates AS (SELECT o.command_id FROM public.auth_outbox o WHERE ((p_lease_purpose='dispatch' AND o.state='pending' AND o.available_at<=p_now AND o.attempt_count<8 AND o.provider_outcome IS DISTINCT FROM 'unknown') OR (p_lease_purpose='reconcile' AND o.state='reconciling' AND o.provider_outcome='unknown' AND o.reconcile_after<=p_now)) ORDER BY o.available_at,o.created_at FOR UPDATE SKIP LOCKED LIMIT p_limit) UPDATE public.auth_outbox o SET state='leased',lease_owner=p_owner,lease_purpose=p_lease_purpose,lease_version=o.lease_version+1,lease_expires_at=p_expires,updated_at=p_now FROM candidates c WHERE o.command_id=c.command_id RETURNING o.command_id,o.purpose,o.channel,o.idempotency_key,o.payload,o.attempt_count,o.lease_version; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_record_dispatch_outcome(p_command text,p_owner text,p_version integer,p_outcome text,p_message text,p_error text,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN IF p_outcome NOT IN ('sent','failed','unknown') THEN RAISE EXCEPTION 'auth_outbox_outcome_denied'; END IF; UPDATE public.auth_outbox SET state=CASE WHEN p_outcome='sent' THEN 'completed' WHEN p_outcome='unknown' THEN 'reconciling' WHEN attempt_count+1>=8 THEN 'manual_review' ELSE 'pending' END,provider_outcome=p_outcome,provider_message_id=coalesce(p_message,provider_message_id),result_code=p_error,attempt_count=attempt_count+1,available_at=CASE WHEN p_outcome='failed' THEN p_now+least(3600,power(2,least(attempt_count,10))*30)*interval '1 second' ELSE available_at END,reconcile_after=CASE WHEN p_outcome='unknown' THEN p_now+interval '1 minute' ELSE reconcile_after END,completed_at=CASE WHEN p_outcome='sent' THEN p_now ELSE completed_at END,lease_owner=NULL,lease_purpose=NULL,lease_expires_at=NULL,updated_at=p_now WHERE command_id=p_command AND lease_owner=p_owner AND lease_version=p_version AND lease_purpose='dispatch' AND state='leased'; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_record_reconciliation(p_command text,p_owner text,p_version integer,p_outcome text,p_message text,p_error text,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN IF p_outcome NOT IN ('sent','failed','unknown') THEN RAISE EXCEPTION 'auth_outbox_outcome_denied'; END IF; UPDATE public.auth_outbox SET state=CASE WHEN p_outcome='sent' THEN 'completed' WHEN p_outcome='failed' AND attempt_count<8 THEN 'pending' ELSE 'manual_review' END,provider_outcome=p_outcome,provider_message_id=coalesce(p_message,provider_message_id),result_code=p_error,available_at=CASE WHEN p_outcome='failed' THEN p_now+least(3600,power(2,least(attempt_count,10))*30)*interval '1 second' ELSE available_at END,completed_at=CASE WHEN p_outcome='sent' THEN p_now ELSE completed_at END,lease_owner=NULL,lease_purpose=NULL,lease_expires_at=NULL,updated_at=p_now WHERE command_id=p_command AND lease_owner=p_owner AND lease_version=p_version AND lease_purpose='reconcile' AND state='leased'; END $$;--> statement-breakpoint

REVOKE ALL ON FUNCTION atlas_auth_issue_oauth_transaction(text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz),atlas_auth_consume_oauth_transaction(text,text,text,text,text,timestamptz),atlas_auth_store_supabase_evidence(text,text,text,text,text,boolean,text,timestamptz,timestamptz),atlas_auth_store_crm_evidence(text,text,text,text,text,timestamptz,timestamptz),atlas_auth_authenticate_identity(text,text,text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_issue_invitation(text,text,text,text,text,text,timestamptz,timestamptz),atlas_auth_consume_invitation(text,text,text,timestamptz),atlas_auth_create_session(text,text,text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_list_sessions(text,timestamptz),atlas_auth_rotate_session(text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_revoke_current(text,timestamptz),atlas_auth_revoke_others(text,timestamptz),atlas_auth_append_audit(text,text,text,text,text,jsonb,timestamptz),atlas_auth_admit_and_enqueue(text,text[],integer,integer,text,text,text,jsonb,text,text,text,text,jsonb,timestamptz),atlas_auth_recover_outbox_leases(timestamptz),atlas_auth_lease_outbox(text,text,integer,timestamptz,timestamptz),atlas_auth_record_dispatch_outcome(text,text,integer,text,text,text,timestamptz),atlas_auth_record_reconciliation(text,text,integer,text,text,text,timestamptz) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_issue_oauth_transaction(text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz),atlas_auth_consume_oauth_transaction(text,text,text,text,text,timestamptz),atlas_auth_store_supabase_evidence(text,text,text,text,text,boolean,text,timestamptz,timestamptz),atlas_auth_store_crm_evidence(text,text,text,text,text,timestamptz,timestamptz),atlas_auth_authenticate_identity(text,text,text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_append_audit(text,text,text,text,text,jsonb,timestamptz),atlas_auth_admit_and_enqueue(text,text[],integer,integer,text,text,text,jsonb,text,text,text,text,jsonb,timestamptz) TO atlas_auth_preauth,atlas_auth_gateway;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_issue_invitation(text,text,text,text,text,text,timestamptz,timestamptz),atlas_auth_consume_invitation(text,text,text,timestamptz),atlas_auth_create_session(text,text,text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_list_sessions(text,timestamptz),atlas_auth_rotate_session(text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_revoke_current(text,timestamptz),atlas_auth_revoke_others(text,timestamptz) TO atlas_auth_gateway;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_recover_outbox_leases(timestamptz),atlas_auth_lease_outbox(text,text,integer,timestamptz,timestamptz),atlas_auth_record_dispatch_outcome(text,text,integer,text,text,text,timestamptz),atlas_auth_record_reconciliation(text,text,integer,text,text,text,timestamptz) TO atlas_auth_worker;
