-- M007 server-owned provider protocols and verifiable worker claims.
ALTER TABLE auth_transactions ADD COLUMN nonce_ciphertext text;--> statement-breakpoint
ALTER TABLE auth_transactions ADD COLUMN pkce_verifier_ciphertext text;--> statement-breakpoint
REVOKE ALL ON FUNCTION atlas_auth_issue_oauth_transaction(text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz) FROM atlas_auth_preauth,atlas_auth_gateway;--> statement-breakpoint
DROP FUNCTION atlas_auth_issue_oauth_transaction(text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz);--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_issue_oauth_transaction(p_id text,p_purpose text,p_provider text,p_state text,p_nonce text,p_pkce text,p_browser text,p_redirect text,p_nonce_ciphertext text,p_pkce_ciphertext text,p_return text,p_callback text,p_expires timestamptz,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN IF length(p_id)<16 OR p_purpose NOT IN ('sign_in','link') OR p_provider<>'google' OR length(p_state)<32 OR length(p_nonce)<32 OR length(p_pkce)<32 OR length(p_browser)<32 OR length(p_redirect)<32 OR length(p_nonce_ciphertext)<32 OR length(p_pkce_ciphertext)<32 OR p_return !~ '^/(?!/)' OR p_callback !~ '^https://[^/?#]+/api/auth/oauth/google/callback$' OR p_expires<=p_now OR p_expires>p_now+interval '15 minutes' THEN RAISE EXCEPTION 'auth_oauth_input_denied'; END IF; INSERT INTO public.auth_transactions(id,purpose,provider,state_digest,nonce_digest,pkce_verifier_digest,browser_binding_digest,redirect_hash,nonce_ciphertext,pkce_verifier_ciphertext,return_intent,callback_url,state,expires_at,version,created_at,updated_at) VALUES(p_id,p_purpose,p_provider,p_state,p_nonce,p_pkce,p_browser,p_redirect,p_nonce_ciphertext,p_pkce_ciphertext,p_return,p_callback,'pending',p_expires,1,p_now,p_now); END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_load_oauth_transaction(p_state text,p_browser text,p_now timestamptz) RETURNS TABLE(nonce_ciphertext text,pkce_verifier_ciphertext text) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ SELECT transaction.nonce_ciphertext,transaction.pkce_verifier_ciphertext FROM public.auth_transactions transaction WHERE transaction.state='pending' AND transaction.expires_at>p_now AND transaction.state_digest=p_state AND transaction.browser_binding_digest=p_browser AND transaction.nonce_ciphertext IS NOT NULL AND transaction.pkce_verifier_ciphertext IS NOT NULL $$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION atlas_auth_consume_email_provider_token(p_digest text,p_purpose text,p_now timestamptz) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE inserted text; BEGIN IF length(p_digest)<32 OR p_purpose NOT IN ('verification','recovery') THEN RAISE EXCEPTION 'auth_email_proof_denied'; END IF; INSERT INTO public.auth_proofs(id,purpose,proof_digest,account_id,browser_binding_digest,state,expires_at,consumed_at,version,created_at,updated_at) VALUES(p_digest,p_purpose,p_digest,NULL,NULL,'consumed',p_now+interval '1 day',p_now,1,p_now,p_now) ON CONFLICT(proof_digest) DO NOTHING RETURNING id INTO inserted; RETURN inserted IS NOT NULL; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_establish_email_session(p_account text,p_external text,p_session text,p_family text,p_subject text,p_handle text,p_token_ciphertext text,p_idle timestamptz,p_absolute timestamptz,p_now timestamptz) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ DECLARE account_id text; BEGIN IF length(p_subject)<1 OR length(p_handle)<32 OR length(p_token_ciphertext)<32 OR p_idle<=p_now OR p_absolute<=p_idle THEN RAISE EXCEPTION 'auth_email_session_denied'; END IF; INSERT INTO public.auth_accounts(id,supabase_subject,status,authentication_epoch,access_epoch,policy_epoch,version,created_at,updated_at) VALUES(p_account,p_subject,'active',1,1,1,1,p_now,p_now) ON CONFLICT(supabase_subject) DO UPDATE SET updated_at=excluded.updated_at RETURNING id INTO account_id; INSERT INTO public.auth_external_identities(id,account_id,provider,provider_subject,state,linked_at,version,created_at,updated_at) VALUES(p_external,account_id,'email_password',p_subject,'active',p_now,1,p_now,p_now) ON CONFLICT(provider,provider_subject) DO UPDATE SET updated_at=excluded.updated_at; INSERT INTO public.auth_sessions(id,account_id,handle_digest,family_id,generation,assurance,state,idle_expires_at,absolute_expires_at,version,created_at,updated_at) VALUES(p_session,account_id,p_handle,p_family,1,'aal1','active',p_idle,p_absolute,1,p_now,p_now); INSERT INTO public.auth_provider_vault(id,session_id,ciphertext,key_reference,purpose,version,created_at,updated_at) VALUES(p_session,p_session,p_token_ciphertext,'AUTH_PROVIDER_TOKEN_KEY','email_provider_session',1,p_now,p_now); RETURN account_id; END $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_load_email_provider_token(p_handle text,p_now timestamptz) RETURNS TABLE(ciphertext text) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ SELECT vault.ciphertext FROM public.auth_sessions session JOIN public.auth_provider_vault vault ON vault.session_id=session.id AND vault.purpose='email_provider_session' WHERE session.handle_digest=p_handle AND session.state='active' AND session.idle_expires_at>p_now AND session.absolute_expires_at>p_now $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION atlas_auth_clear_email_provider_token(p_handle text,p_now timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN DELETE FROM public.auth_provider_vault vault USING public.auth_sessions session WHERE vault.session_id=session.id AND session.handle_digest=p_handle; END $$;--> statement-breakpoint

DROP FUNCTION atlas_auth_lease_outbox(text,text,integer,timestamptz,timestamptz);--> statement-breakpoint
CREATE FUNCTION atlas_auth_lease_outbox(p_owner text,p_lease_purpose text,p_limit integer,p_now timestamptz,p_expires timestamptz) RETURNS TABLE(command_id text,purpose text,channel varchar,idempotency_key varchar,payload jsonb,attempt_count integer,lease_version integer,lease_owner text,lease_purpose varchar) LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public SET row_security=off AS $$ BEGIN IF length(p_owner)<8 OR p_lease_purpose NOT IN ('dispatch','reconcile') OR p_limit<1 OR p_limit>100 OR p_expires<=p_now THEN RAISE EXCEPTION 'auth_outbox_lease_denied'; END IF; RETURN QUERY WITH candidates AS (SELECT o.command_id FROM public.auth_outbox o WHERE ((p_lease_purpose='dispatch' AND o.state='pending' AND o.available_at<=p_now AND o.attempt_count<8 AND o.provider_outcome IS DISTINCT FROM 'unknown') OR (p_lease_purpose='reconcile' AND o.state='reconciling' AND o.provider_outcome='unknown' AND o.reconcile_after<=p_now)) ORDER BY o.available_at,o.created_at FOR UPDATE SKIP LOCKED LIMIT p_limit) UPDATE public.auth_outbox o SET state='leased',lease_owner=p_owner,lease_purpose=p_lease_purpose,lease_version=o.lease_version+1,lease_expires_at=p_expires,updated_at=p_now FROM candidates c WHERE o.command_id=c.command_id RETURNING o.command_id,o.purpose,o.channel,o.idempotency_key,o.payload,o.attempt_count,o.lease_version,o.lease_owner,o.lease_purpose; END $$;--> statement-breakpoint

REVOKE ALL ON FUNCTION atlas_auth_issue_oauth_transaction(text,text,text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz),atlas_auth_load_oauth_transaction(text,text,timestamptz),atlas_auth_consume_email_provider_token(text,text,timestamptz),atlas_auth_establish_email_session(text,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz),atlas_auth_load_email_provider_token(text,timestamptz),atlas_auth_clear_email_provider_token(text,timestamptz),atlas_auth_lease_outbox(text,text,integer,timestamptz,timestamptz) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_issue_oauth_transaction(text,text,text,text,text,text,text,text,text,text,text,text,timestamptz,timestamptz),atlas_auth_load_oauth_transaction(text,text,timestamptz),atlas_auth_consume_email_provider_token(text,text,timestamptz),atlas_auth_establish_email_session(text,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz) TO atlas_auth_preauth,atlas_auth_gateway;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_load_email_provider_token(text,timestamptz),atlas_auth_clear_email_provider_token(text,timestamptz) TO atlas_auth_gateway;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION atlas_auth_lease_outbox(text,text,integer,timestamptz,timestamptz) TO atlas_auth_worker;
