DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'atlas_bookkeeping_gateway') THEN
    CREATE ROLE atlas_bookkeeping_gateway NOLOGIN NOBYPASSRLS;
  END IF;
END $$;
ALTER ROLE atlas_bookkeeping_gateway NOBYPASSRLS;

CREATE TABLE public.bookkeeping_engagements (id text PRIMARY KEY, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), accounting_entity_ref text NOT NULL, service_type varchar(32) NOT NULL CHECK (service_type IN ('monthly_bookkeeping','quarterly_bookkeeping','annual_cleanup','catch_up_bookkeeping','cleanup_bookkeeping','bookkeeping_cleanup','tax_ready_books','transaction_categorization','bank_reconciliation','financial_reporting','custom_bookkeeping_service')), bookkeeping_frequency varchar(16) NOT NULL CHECK (bookkeeping_frequency IN ('monthly','quarterly','annual','custom')), accounting_basis varchar(16) NOT NULL CHECK (accounting_basis IN ('cash','accrual')), book_start_on timestamptz NOT NULL, fiscal_year_end_month integer NOT NULL CHECK (fiscal_year_end_month BETWEEN 1 AND 12), monthly_transaction_allowance integer CHECK (monthly_transaction_allowance>=0), reporting_frequency varchar(16) NOT NULL CHECK (reporting_frequency IN ('monthly','quarterly','annual','custom')), close_policy_ref varchar(128), external_accounting_system varchar(24) NOT NULL DEFAULT 'disabled' CHECK (external_accounting_system='disabled'), status varchar(32) NOT NULL CHECK (status IN ('setup_in_progress','active','paused','closed')), provider_connections_enabled boolean NOT NULL DEFAULT false CHECK (provider_connections_enabled=false), tax_integration_enabled boolean NOT NULL DEFAULT false CHECK (tax_integration_enabled=false), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(owner_account_id,context_ref,accounting_entity_ref));
CREATE TABLE public.accounting_books (id text PRIMARY KEY, engagement_id text NOT NULL REFERENCES public.bookkeeping_engagements(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), accounting_entity_ref text NOT NULL, accounting_basis varchar(16) NOT NULL CHECK (accounting_basis IN ('cash','accrual')), currency varchar(3) NOT NULL CHECK (currency='USD'), fiscal_year_start_month integer NOT NULL CHECK (fiscal_year_start_month BETWEEN 1 AND 12), status varchar(16) NOT NULL CHECK (status IN ('setup','active','soft_closed','hard_closed','archived')), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(engagement_id,accounting_entity_ref));
CREATE TABLE public.accounting_periods (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), period_start timestamptz NOT NULL, period_end timestamptz NOT NULL CHECK (period_end>period_start), status varchar(16) NOT NULL CHECK (status IN ('open','soft_closed','hard_closed')), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(book_id,period_start));
CREATE TABLE public.chart_accounts (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), code varchar(64) NOT NULL, name text NOT NULL, category varchar(16) NOT NULL CHECK (category IN ('asset','liability','equity','income','expense')), active boolean NOT NULL, system_account boolean NOT NULL CHECK (system_account=false OR active=true), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(book_id,code));
CREATE TABLE public.financial_account_registry (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), account_name text NOT NULL, account_type varchar(24) NOT NULL CHECK (account_type IN ('bank','credit_card','loan','cash','other')), currency varchar(3) NOT NULL CHECK (currency='USD'), provider_connection_status varchar(24) NOT NULL CHECK (provider_connection_status IN ('not_connected','disabled')), active boolean NOT NULL, version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.source_transactions (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, financial_account_id text NOT NULL REFERENCES public.financial_account_registry(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), source_reference varchar(128) NOT NULL, occurred_on timestamptz NOT NULL, amount_minor bigint NOT NULL CHECK (amount_minor<>0), direction varchar(16) NOT NULL CHECK (direction IN ('inflow','outflow')), description text NOT NULL, pending boolean NOT NULL, state varchar(24) NOT NULL CHECK (state IN ('imported','review_required','reconciled','excluded')), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(financial_account_id,source_reference));
CREATE TABLE public.journal_entries (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, period_id text NOT NULL REFERENCES public.accounting_periods(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), source_transaction_id text REFERENCES public.source_transactions(id) ON DELETE RESTRICT, status varchar(16) NOT NULL CHECK (status IN ('draft','proposed','posted','voided')), memo text, posted_at timestamptz, version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), CHECK ((status='posted' AND posted_at IS NOT NULL) OR (status<>'posted' AND posted_at IS NULL)));
CREATE TABLE public.journal_entry_lines (id text PRIMARY KEY, journal_entry_id text NOT NULL REFERENCES public.journal_entries(id) ON DELETE RESTRICT, account_id text NOT NULL REFERENCES public.chart_accounts(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), ordinal integer NOT NULL CHECK (ordinal>0), debit_minor bigint NOT NULL CHECK (debit_minor>=0), credit_minor bigint NOT NULL CHECK (credit_minor>=0), memo text, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(journal_entry_id,ordinal), CHECK ((debit_minor>0 AND credit_minor=0) OR (credit_minor>0 AND debit_minor=0)));
CREATE TABLE public.reconciliation_sessions (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, financial_account_id text NOT NULL REFERENCES public.financial_account_registry(id) ON DELETE RESTRICT, period_id text NOT NULL REFERENCES public.accounting_periods(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), statement_ending_balance_minor bigint NOT NULL, difference_minor bigint NOT NULL, status varchar(24) NOT NULL CHECK (status IN ('draft','in_progress','difference_detected','review_required','completed','locked')), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(financial_account_id,period_id));
CREATE TABLE public.bookkeeping_audit_events (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), event_type varchar(80) NOT NULL CHECK (char_length(event_type)>0), resource_reference text NOT NULL, correlation_id varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.bookkeeping_outbox (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), event_type varchar(80) NOT NULL, state varchar(16) NOT NULL CHECK (state IN ('pending','processing','delivered','failed')), attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 3), claimed_at timestamptz, last_error_code varchar(80), correlation_id varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), delivered_at timestamptz);

CREATE INDEX bookkeeping_engagements_owner_context_idx ON public.bookkeeping_engagements(owner_account_id,context_ref,updated_at); CREATE INDEX accounting_books_owner_context_idx ON public.accounting_books(owner_account_id,context_ref); CREATE INDEX accounting_periods_book_status_idx ON public.accounting_periods(book_id,status,period_end); CREATE INDEX chart_accounts_book_category_idx ON public.chart_accounts(book_id,category,active); CREATE INDEX financial_account_registry_book_active_idx ON public.financial_account_registry(book_id,active); CREATE INDEX source_transactions_book_occurred_idx ON public.source_transactions(book_id,occurred_on); CREATE INDEX journal_entries_book_period_idx ON public.journal_entries(book_id,period_id,status); CREATE INDEX journal_entry_lines_account_idx ON public.journal_entry_lines(account_id,created_at); CREATE INDEX reconciliation_sessions_book_status_idx ON public.reconciliation_sessions(book_id,status,updated_at); CREATE INDEX bookkeeping_audit_events_book_created_idx ON public.bookkeeping_audit_events(book_id,created_at); CREATE INDEX bookkeeping_outbox_state_created_idx ON public.bookkeeping_outbox(state,created_at);

CREATE OR REPLACE FUNCTION public.bookkeeping_journal_entries_posted_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status='posted' THEN RAISE EXCEPTION 'posted journal entries are immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER bookkeeping_journal_entries_posted_immutable BEFORE UPDATE OR DELETE ON public.journal_entries FOR EACH ROW EXECUTE FUNCTION public.bookkeeping_journal_entries_posted_immutable();

ALTER TABLE public.bookkeeping_engagements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_engagements FORCE ROW LEVEL SECURITY; ALTER TABLE public.accounting_books ENABLE ROW LEVEL SECURITY; ALTER TABLE public.accounting_books FORCE ROW LEVEL SECURITY; ALTER TABLE public.accounting_periods ENABLE ROW LEVEL SECURITY; ALTER TABLE public.accounting_periods FORCE ROW LEVEL SECURITY; ALTER TABLE public.chart_accounts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.chart_accounts FORCE ROW LEVEL SECURITY; ALTER TABLE public.financial_account_registry ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_account_registry FORCE ROW LEVEL SECURITY; ALTER TABLE public.source_transactions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.source_transactions FORCE ROW LEVEL SECURITY; ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY; ALTER TABLE public.journal_entries FORCE ROW LEVEL SECURITY; ALTER TABLE public.journal_entry_lines ENABLE ROW LEVEL SECURITY; ALTER TABLE public.journal_entry_lines FORCE ROW LEVEL SECURITY; ALTER TABLE public.reconciliation_sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.reconciliation_sessions FORCE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_audit_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_audit_events FORCE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_outbox ENABLE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_outbox FORCE ROW LEVEL SECURITY;

CREATE POLICY bookkeeping_engagements_server_gateway_only ON public.bookkeeping_engagements FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY accounting_books_server_gateway_only ON public.accounting_books FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY accounting_periods_server_gateway_only ON public.accounting_periods FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY chart_accounts_server_gateway_only ON public.chart_accounts FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY financial_account_registry_server_gateway_only ON public.financial_account_registry FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY source_transactions_server_gateway_only ON public.source_transactions FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY journal_entries_server_gateway_only ON public.journal_entries FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY journal_entry_lines_server_gateway_only ON public.journal_entry_lines FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY reconciliation_sessions_server_gateway_only ON public.reconciliation_sessions FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY bookkeeping_audit_events_server_gateway_only ON public.bookkeeping_audit_events FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY bookkeeping_outbox_server_gateway_only ON public.bookkeeping_outbox FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true);

REVOKE ALL ON public.bookkeeping_engagements, public.accounting_books, public.accounting_periods, public.chart_accounts, public.financial_account_registry, public.source_transactions, public.journal_entries, public.journal_entry_lines, public.reconciliation_sessions, public.bookkeeping_audit_events, public.bookkeeping_outbox FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bookkeeping_engagements, public.accounting_books, public.accounting_periods, public.chart_accounts, public.financial_account_registry, public.source_transactions, public.journal_entries, public.journal_entry_lines, public.reconciliation_sessions, public.bookkeeping_audit_events, public.bookkeeping_outbox TO atlas_bookkeeping_gateway;

CREATE TABLE public.accounting_close_requests (id text PRIMARY KEY, book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, period_id text NOT NULL REFERENCES public.accounting_periods(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), requested_by_account_id text NOT NULL, reviewer_account_id text, status varchar(16) NOT NULL CHECK (status IN ('requested','approved','rejected')), reason text, reviewed_at timestamptz, version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(period_id));
CREATE INDEX accounting_close_requests_book_status_idx ON public.accounting_close_requests(book_id,status);
ALTER TABLE public.accounting_close_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.accounting_close_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY accounting_close_requests_server_gateway_only ON public.accounting_close_requests FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true);
REVOKE ALL ON public.accounting_close_requests FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.accounting_close_requests TO atlas_bookkeeping_gateway;

CREATE TABLE public.accounting_entities (id text PRIMARY KEY, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), organization_ref text, legal_entity_type varchar(32) NOT NULL CHECK (legal_entity_type IN ('individual','sole_proprietorship','llc','corporation','partnership','other')), classification varchar(16) NOT NULL CHECK (classification IN ('business','personal','mixed','unknown')), display_name text NOT NULL, tax_identifier_token_ref text, currency varchar(3) NOT NULL CHECK (currency='USD'), country varchar(2) NOT NULL CHECK (country='US'), base_jurisdiction varchar(16), fiscal_year_end_month integer NOT NULL CHECK (fiscal_year_end_month BETWEEN 1 AND 12), status varchar(16) NOT NULL CHECK (status IN ('setup','active','archived')), version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.bookkeeping_cases (id text PRIMARY KEY, case_number varchar(64) NOT NULL UNIQUE, engagement_id text NOT NULL REFERENCES public.bookkeeping_engagements(id) ON DELETE RESTRICT, accounting_book_id text NOT NULL REFERENCES public.accounting_books(id) ON DELETE RESTRICT, current_period_id text REFERENCES public.accounting_periods(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), accounting_entity_ref text NOT NULL, organization_ref text, service_order_ref text, assigned_bookkeeper_ref text, assigned_reviewer_ref text, status varchar(32) NOT NULL CHECK (status IN ('draft','setup_pending','opening_balances_pending','active','period_processing','questions_pending','review_pending','client_action_required','paused','completed','cancelled','archived')), closed_at timestamptz, version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(engagement_id,accounting_book_id), CHECK ((status IN ('completed','cancelled','archived')) = (closed_at IS NOT NULL)));
CREATE INDEX accounting_entities_owner_context_status_idx ON public.accounting_entities(owner_account_id,context_ref,status); CREATE INDEX bookkeeping_cases_owner_context_status_idx ON public.bookkeeping_cases(owner_account_id,context_ref,status);
ALTER TABLE public.accounting_entities ENABLE ROW LEVEL SECURITY; ALTER TABLE public.accounting_entities FORCE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_cases ENABLE ROW LEVEL SECURITY; ALTER TABLE public.bookkeeping_cases FORCE ROW LEVEL SECURITY;
CREATE POLICY accounting_entities_server_gateway_only ON public.accounting_entities FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true); CREATE POLICY bookkeeping_cases_server_gateway_only ON public.bookkeeping_cases FOR ALL TO atlas_bookkeeping_gateway USING (true) WITH CHECK (true);
REVOKE ALL ON public.accounting_entities, public.bookkeeping_cases FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.accounting_entities, public.bookkeeping_cases TO atlas_bookkeeping_gateway;

ALTER TABLE public.bookkeeping_engagements ADD CONSTRAINT bookkeeping_engagements_accounting_entity_fk FOREIGN KEY (accounting_entity_ref) REFERENCES public.accounting_entities(id) ON DELETE RESTRICT;
ALTER TABLE public.accounting_books ADD CONSTRAINT accounting_books_accounting_entity_fk FOREIGN KEY (accounting_entity_ref) REFERENCES public.accounting_entities(id) ON DELETE RESTRICT;
ALTER TABLE public.bookkeeping_cases ADD CONSTRAINT bookkeeping_cases_accounting_entity_fk FOREIGN KEY (accounting_entity_ref) REFERENCES public.accounting_entities(id) ON DELETE RESTRICT;
