DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'atlas_formation_gateway') THEN
    CREATE ROLE atlas_formation_gateway NOLOGIN NOBYPASSRLS;
  END IF;
END $$;
ALTER ROLE atlas_formation_gateway NOBYPASSRLS;

CREATE TABLE public.formation_cases (id text PRIMARY KEY, case_number varchar(64) NOT NULL UNIQUE, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), client_ref text NOT NULL, organization_ref text, service_order_ref text NOT NULL, product_code varchar(96) NOT NULL, entity_type varchar(48) NOT NULL CHECK (entity_type IN ('limited_liability_company','corporation','nonprofit_corporation','professional_entity','partnership_registration','foreign_qualification','series_llc','other_supported_entity')), formation_jurisdiction varchar(24) NOT NULL, delivery_model varchar(32) NOT NULL CHECK (delivery_model IN ('sg_service','sg_managed_with_partner','marketplace_referral','education_only','future_or_conditional')), status varchar(32) NOT NULL CHECK (status IN ('draft','intake_pending','intake_in_progress','eligibility_review','name_review','formation_data_pending','document_preparation','internal_review','client_review','signature_pending','payment_pending','ready_to_file','filing_in_progress','state_processing','state_action_required','approved','rejected','post_formation','completed','cancelled','archived')), assigned_specialist_ref text, assigned_reviewer_ref text, partner_ref text, version integer NOT NULL CHECK (version>0), completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.formation_requirement_versions (id text PRIMARY KEY, jurisdiction varchar(24) NOT NULL, entity_type varchar(48) NOT NULL, rule_category varchar(48) NOT NULL, rule_key varchar(96) NOT NULL, rule_value jsonb NOT NULL, verification_status varchar(24) NOT NULL CHECK (verification_status IN ('draft','under_review','verified','stale','retired')), source_reference text NOT NULL, effective_from timestamptz NOT NULL, effective_to timestamptz, version integer NOT NULL CHECK (version>0), verified_at timestamptz, verified_by text, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(jurisdiction,entity_type,rule_key,version), CHECK (effective_to IS NULL OR effective_to>effective_from));
CREATE TABLE public.formation_requirement_snapshots (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, snapshot_hash varchar(64) NOT NULL, requirement_ids jsonb NOT NULL, captured_at timestamptz NOT NULL, invalidated_at timestamptz, invalidation_reason varchar(80), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(formation_case_id,snapshot_hash));
CREATE TABLE public.formation_parties (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, party_ref text NOT NULL, party_role varchar(40) NOT NULL, ownership_basis_points integer, voting_basis_points integer, management_role varchar(40), status varchar(24) NOT NULL, version integer NOT NULL CHECK (version>0), created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(formation_case_id,party_ref,party_role), CHECK (ownership_basis_points IS NULL OR ownership_basis_points BETWEEN 1 AND 10000));
CREATE TABLE public.formation_name_candidates (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, candidate_name text NOT NULL, normalized_name text NOT NULL, rank integer NOT NULL CHECK (rank>0), source varchar(24) NOT NULL, status varchar(40) NOT NULL, conflict_reason text, evidence_reference text, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(formation_case_id,rank));
CREATE TABLE public.formation_packages (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, requirement_snapshot_id text NOT NULL REFERENCES public.formation_requirement_snapshots(id) ON DELETE RESTRICT, template_version varchar(96) NOT NULL, document_hash varchar(64) NOT NULL, document_refs jsonb NOT NULL, state varchar(24) NOT NULL CHECK (state IN ('prepared','invalidated','authorized')), generated_at timestamptz NOT NULL, invalidated_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(formation_case_id,document_hash));
CREATE TABLE public.formation_authorizations (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, formation_package_id text NOT NULL REFERENCES public.formation_packages(id) ON DELETE RESTRICT, document_hash varchar(64) NOT NULL, authorization_type varchar(48) NOT NULL, signer_ref text NOT NULL, signature_evidence_ref text, status varchar(24) NOT NULL CHECK (status IN ('pending','accepted','revoked','expired')), accepted_at timestamptz, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(formation_package_id,signer_ref,authorization_type));
CREATE TABLE public.formation_filing_attempts (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, formation_package_id text NOT NULL REFERENCES public.formation_packages(id) ON DELETE RESTRICT, provider_code varchar(64) NOT NULL, idempotency_key varchar(128) NOT NULL, package_hash varchar(64) NOT NULL, status varchar(32) NOT NULL CHECK (status IN ('prepared','submitted','state_processing','rejected','approved','blocked')), government_fee_minor bigint NOT NULL CHECK (government_fee_minor>=0), sg_service_fee_minor bigint NOT NULL CHECK (sg_service_fee_minor>=0), partner_fee_minor bigint NOT NULL CHECK (partner_fee_minor>=0), submitted_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), CONSTRAINT formation_filing_attempts_case_idempotency_unique UNIQUE(formation_case_id,idempotency_key));
CREATE TABLE public.formation_filing_outcomes (id text PRIMARY KEY, filing_attempt_id text NOT NULL REFERENCES public.formation_filing_attempts(id) ON DELETE RESTRICT, outcome_kind varchar(32) NOT NULL CHECK (outcome_kind IN ('rejected','approved','state_processing')), official_reference text NOT NULL, reason text, official_document_refs jsonb NOT NULL, raw_status_reference text, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.formation_handoffs (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, destination varchar(24) NOT NULL CHECK (destination IN ('ein','compliance','bookkeeping','tax','funding','banking')), approval_reference text NOT NULL, idempotency_key varchar(160) NOT NULL UNIQUE, status varchar(24) NOT NULL CHECK (status IN ('pending','accepted','blocked','cancelled')), accepted_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), CONSTRAINT formation_handoffs_case_destination_approval_unique UNIQUE(formation_case_id,destination,approval_reference));
CREATE TABLE public.formation_audit_events (id text PRIMARY KEY, formation_case_id text NOT NULL REFERENCES public.formation_cases(id) ON DELETE RESTRICT, owner_account_id text NOT NULL, context_ref text NOT NULL, authorization_epoch bigint NOT NULL CHECK (authorization_epoch>=0), policy_epoch bigint NOT NULL CHECK (policy_epoch>=0), event_type varchar(96) NOT NULL, actor_ref text NOT NULL, resource_ref text NOT NULL, correlation_id varchar(128) NOT NULL, source varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp());

CREATE INDEX formation_cases_owner_context_status_idx ON public.formation_cases(owner_account_id,context_ref,status); CREATE INDEX formation_requirement_versions_current_idx ON public.formation_requirement_versions(jurisdiction,entity_type,rule_key,effective_from); CREATE INDEX formation_requirement_snapshots_case_captured_idx ON public.formation_requirement_snapshots(formation_case_id,captured_at); CREATE INDEX formation_name_candidates_case_status_idx ON public.formation_name_candidates(formation_case_id,status); CREATE INDEX formation_packages_case_state_idx ON public.formation_packages(formation_case_id,state); CREATE INDEX formation_filing_attempts_case_status_idx ON public.formation_filing_attempts(formation_case_id,status); CREATE INDEX formation_filing_outcomes_attempt_occurred_idx ON public.formation_filing_outcomes(filing_attempt_id,occurred_at); CREATE INDEX formation_audit_events_case_created_idx ON public.formation_audit_events(formation_case_id,created_at);

CREATE OR REPLACE FUNCTION public.formation_filing_outcomes_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'formation filing outcomes are immutable'; END $$;
CREATE TRIGGER formation_filing_outcomes_immutable BEFORE UPDATE OR DELETE ON public.formation_filing_outcomes FOR EACH ROW EXECUTE FUNCTION public.formation_filing_outcomes_immutable();

ALTER TABLE public.formation_cases ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_cases FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_requirement_versions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_requirement_versions FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_requirement_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_requirement_snapshots FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_parties ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_parties FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_name_candidates ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_name_candidates FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_packages ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_packages FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_authorizations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_authorizations FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_filing_attempts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_filing_attempts FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_filing_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_filing_outcomes FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_handoffs ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_handoffs FORCE ROW LEVEL SECURITY; ALTER TABLE public.formation_audit_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.formation_audit_events FORCE ROW LEVEL SECURITY;

CREATE POLICY formation_cases_server_gateway_only ON public.formation_cases FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_requirement_versions_server_gateway_only ON public.formation_requirement_versions FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_requirement_snapshots_server_gateway_only ON public.formation_requirement_snapshots FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_parties_server_gateway_only ON public.formation_parties FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_name_candidates_server_gateway_only ON public.formation_name_candidates FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_packages_server_gateway_only ON public.formation_packages FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_authorizations_server_gateway_only ON public.formation_authorizations FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_filing_attempts_server_gateway_only ON public.formation_filing_attempts FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_filing_outcomes_server_gateway_only ON public.formation_filing_outcomes FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_handoffs_server_gateway_only ON public.formation_handoffs FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true); CREATE POLICY formation_audit_events_server_gateway_only ON public.formation_audit_events FOR ALL TO atlas_formation_gateway USING (true) WITH CHECK (true);

REVOKE ALL ON public.formation_cases, public.formation_requirement_versions, public.formation_requirement_snapshots, public.formation_parties, public.formation_name_candidates, public.formation_packages, public.formation_authorizations, public.formation_filing_attempts, public.formation_filing_outcomes, public.formation_handoffs, public.formation_audit_events FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formation_cases, public.formation_requirement_versions, public.formation_requirement_snapshots, public.formation_parties, public.formation_name_candidates, public.formation_packages, public.formation_authorizations, public.formation_filing_attempts, public.formation_filing_outcomes, public.formation_handoffs, public.formation_audit_events TO atlas_formation_gateway;
