-- M036 Home Buying Assistance controlled foundation. Author only; do not execute without approved migration, backups and RLS verification.
CREATE ROLE atlas_homebuying_gateway NOLOGIN NOBYPASSRLS;
CREATE TABLE homebuyer_engagements (id text PRIMARY KEY, client_id text NOT NULL, service_order_id text NOT NULL, service_type text NOT NULL, delivery_model text NOT NULL, status text NOT NULL, assigned_specialist_id text, reviewer_id text, opened_at timestamptz NOT NULL, completed_at timestamptz, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE homebuyer_cases (id text PRIMARY KEY, case_number text NOT NULL UNIQUE, engagement_id text NOT NULL, client_id text NOT NULL, homebuyer_profile_id text, status text NOT NULL, priority text NOT NULL, assigned_to text, reviewer_id text, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, completed_at timestamptz);
CREATE TABLE homebuyer_profiles (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, profile_version integer NOT NULL, verification_status text NOT NULL, profile jsonb NOT NULL, sources jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, UNIQUE(homebuyer_case_id, profile_version));
CREATE TABLE homebuyer_financial_profiles (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, profile_version integer NOT NULL, period_start timestamptz NOT NULL, period_end timestamptz NOT NULL, verification_status text NOT NULL, financial_profile jsonb NOT NULL, sources jsonb NOT NULL, created_at timestamptz NOT NULL, UNIQUE(homebuyer_case_id, profile_version));
CREATE TABLE housing_programs (id text PRIMARY KEY, code text NOT NULL UNIQUE, family text NOT NULL, jurisdiction text NOT NULL, status text NOT NULL, current_version_id text, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE housing_program_versions (id text PRIMARY KEY, program_id text NOT NULL, version integer NOT NULL, status text NOT NULL, availability text NOT NULL, configuration jsonb NOT NULL, sources jsonb NOT NULL, verified_at timestamptz, next_review_at timestamptz, created_at timestamptz NOT NULL, UNIQUE(program_id, version));
CREATE TABLE homebuyer_program_screenings (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, program_version_id text NOT NULL, profile_version integer NOT NULL, financial_profile_version integer, status text NOT NULL, result jsonb NOT NULL, evaluated_at timestamptz NOT NULL);
CREATE TABLE homebuyer_consents (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, partner_id text, purpose text NOT NULL, status text NOT NULL, data_categories jsonb NOT NULL, disclosure_version_ids jsonb NOT NULL, accepted_at timestamptz, expires_at timestamptz, withdrawn_at timestamptz);
CREATE TABLE homebuyer_referrals (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, lender_id text NOT NULL, program_version_id text, consent_id text NOT NULL, tracking_reference text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE homebuyer_property_candidates (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, address_reference text NOT NULL, listing_reference text, price_cents integer, currency text, status text NOT NULL, sources jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE homebuyer_closing_records (id text PRIMARY KEY, homebuyer_case_id text NOT NULL, property_candidate_id text NOT NULL, closing_status text NOT NULL, closing_date timestamptz, final_cash_to_close_cents integer CHECK(final_cash_to_close_cents >= 0), currency text, source_document_id text, verified_at timestamptz);
CREATE TABLE homebuyer_audit_events (id text PRIMARY KEY, homebuyer_case_id text, action text NOT NULL, actor_type text NOT NULL, actor_id text, correlation_id text NOT NULL, safe_metadata jsonb NOT NULL, occurred_at timestamptz NOT NULL);
CREATE INDEX homebuyer_cases_client_status_idx ON homebuyer_cases(client_id, status); CREATE INDEX homebuyer_program_screenings_case_idx ON homebuyer_program_screenings(homebuyer_case_id); CREATE INDEX homebuyer_referrals_case_idx ON homebuyer_referrals(homebuyer_case_id); CREATE INDEX homebuyer_property_candidates_case_idx ON homebuyer_property_candidates(homebuyer_case_id); CREATE INDEX homebuyer_closing_records_case_idx ON homebuyer_closing_records(homebuyer_case_id); CREATE INDEX homebuyer_audit_events_case_idx ON homebuyer_audit_events(homebuyer_case_id);
ALTER TABLE homebuyer_engagements ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_cases ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_financial_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE housing_programs ENABLE ROW LEVEL SECURITY; ALTER TABLE housing_program_versions ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_program_screenings ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_consents ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_referrals ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_property_candidates ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_closing_records ENABLE ROW LEVEL SECURITY; ALTER TABLE homebuyer_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE homebuyer_engagements FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_cases FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_profiles FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_financial_profiles FORCE ROW LEVEL SECURITY; ALTER TABLE housing_programs FORCE ROW LEVEL SECURITY; ALTER TABLE housing_program_versions FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_program_screenings FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_consents FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_referrals FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_property_candidates FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_closing_records FORCE ROW LEVEL SECURITY; ALTER TABLE homebuyer_audit_events FORCE ROW LEVEL SECURITY;
CREATE POLICY homebuyer_engagements_gateway_only ON homebuyer_engagements TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_cases_gateway_only ON homebuyer_cases TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_profiles_gateway_only ON homebuyer_profiles TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_financial_profiles_gateway_only ON homebuyer_financial_profiles TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY housing_programs_gateway_only ON housing_programs TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY housing_program_versions_gateway_only ON housing_program_versions TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_program_screenings_gateway_only ON homebuyer_program_screenings TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_consents_gateway_only ON homebuyer_consents TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_referrals_gateway_only ON homebuyer_referrals TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_property_candidates_gateway_only ON homebuyer_property_candidates TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_closing_records_gateway_only ON homebuyer_closing_records TO atlas_homebuying_gateway USING(false) WITH CHECK(false); CREATE POLICY homebuyer_audit_events_gateway_only ON homebuyer_audit_events TO atlas_homebuying_gateway USING(false) WITH CHECK(false);
