-- M039 CreditCardBroker controlled foundation. Authored only; never executed.
-- No credential, network, redirect, application, or provider activation is created by this migration.
CREATE ROLE atlas_creditcardbroker_gateway NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
ALTER ROLE atlas_creditcardbroker_gateway NOBYPASSRLS;
CREATE TABLE public.ccb_rule_snapshots (id text PRIMARY KEY, source_url text NOT NULL, source_type varchar(48) NOT NULL, rule_version varchar(128) NOT NULL, content_hash varchar(128) NOT NULL, status varchar(24) NOT NULL, reviewed_by text, reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(source_url, rule_version));
CREATE TABLE public.ccb_integration_modes (id text PRIMARY KEY, rule_snapshot_id text NOT NULL, mode varchar(48) NOT NULL, authorization_status varchar(32) NOT NULL, approved_domains jsonb NOT NULL, approved_surfaces jsonb NOT NULL, capabilities jsonb NOT NULL, status varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_approved_surfaces (id text PRIMARY KEY, rule_snapshot_id text NOT NULL, domain varchar(255) NOT NULL, path_pattern text, surface_type varchar(48) NOT NULL, approval_status varchar(24) NOT NULL, disclosure_set_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_partner_accounts (id text PRIMARY KEY, marketplace_provider_id text NOT NULL UNIQUE, external_account_reference text NOT NULL, status varchar(24) NOT NULL, tax_document_status varchar(24) NOT NULL, tax_document_reference text, integration_mode_ids jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_advertisers (id text PRIMARY KEY, network_provider_id text NOT NULL, external_advertiser_id text, legal_name varchar(256) NOT NULL, display_name varchar(256) NOT NULL, provider_type varchar(48) NOT NULL, status varchar(24) NOT NULL, source_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_offer_sources (id text PRIMARY KEY, external_offer_id text NOT NULL, advertiser_id text NOT NULL, source_method varchar(48) NOT NULL, source_payload_reference text NOT NULL, raw_payload_hash varchar(128) NOT NULL, source_version varchar(128) NOT NULL, status varchar(24) NOT NULL, retrieved_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(external_offer_id, source_version));
CREATE TABLE public.ccb_offers (id text PRIMARY KEY, external_offer_id text NOT NULL UNIQUE, advertiser_id text NOT NULL, source_id text NOT NULL, product_family varchar(64) NOT NULL, status varchar(32) NOT NULL, freshness_status varchar(16) NOT NULL, current_version_id text, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_offer_versions (id text PRIMARY KEY, offer_id text NOT NULL, version integer NOT NULL CHECK (version > 0), content_snapshot jsonb NOT NULL, terms_snapshot jsonb NOT NULL, disclosure_snapshot jsonb NOT NULL, source_snapshot jsonb NOT NULL, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(offer_id, version));
CREATE TABLE public.ccb_affiliate_links (id text PRIMARY KEY, offer_id text NOT NULL, external_tracking_url text NOT NULL, destination_host varchar(255) NOT NULL, tracking_parameter_names jsonb NOT NULL, source_snapshot jsonb NOT NULL, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_journeys (id text PRIMARY KEY, marketplace_journey_id text NOT NULL UNIQUE, offer_id text NOT NULL, display_id text NOT NULL, client_reference text, consent_id text, status varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_conversions (id text PRIMARY KEY, journey_id text NOT NULL, definition_id text NOT NULL, external_event_reference varchar(160) NOT NULL UNIQUE, status varchar(24) NOT NULL, evidence_type varchar(32), evidence_reference text, received_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_commission_rules (id text PRIMARY KEY, partner_account_id text NOT NULL, conversion_definition_id text NOT NULL, version integer NOT NULL CHECK (version > 0), calculation_type varchar(32) NOT NULL, amount_cents integer, basis_points integer, currency varchar(3) NOT NULL, status varchar(24) NOT NULL, source_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_commissions (id text PRIMARY KEY, conversion_id text NOT NULL, rule_id text NOT NULL, status varchar(24) NOT NULL, amount_cents integer, qualifying_evidence_reference text, currency varchar(3) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.ccb_findings (id text PRIMARY KEY, type varchar(48) NOT NULL, resource_type varchar(64) NOT NULL, resource_id text NOT NULL, severity varchar(16) NOT NULL, status varchar(48) NOT NULL, blocking boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
ALTER TABLE public.ccb_rule_snapshots ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_integration_modes ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_approved_surfaces ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_partner_accounts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_advertisers ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_offer_sources ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_offers ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_offer_versions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_affiliate_links ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_journeys ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_conversions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_commission_rules ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_commissions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ccb_findings ENABLE ROW LEVEL SECURITY;
CREATE POLICY ccb_deny_direct_offers ON public.ccb_offers AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false); CREATE POLICY ccb_deny_direct_journeys ON public.ccb_journeys AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false); CREATE POLICY ccb_deny_direct_commissions ON public.ccb_commissions AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false);