-- M040 Partner Management controlled foundation. Authored only; never executed.
CREATE ROLE atlas_partner_gateway NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT; ALTER ROLE atlas_partner_gateway NOBYPASSRLS;
CREATE TABLE public.partners (id text PRIMARY KEY, organization_id text NOT NULL UNIQUE, code varchar(96) NOT NULL UNIQUE, legal_name varchar(256) NOT NULL, display_name varchar(256) NOT NULL, partner_type varchar(64) NOT NULL, status varchar(32) NOT NULL, verification_status varchar(32) NOT NULL, risk_tier varchar(16) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_relationships (id text PRIMARY KEY, partner_id text NOT NULL, relationship_type varchar(48) NOT NULL, owner_id text NOT NULL, status varchar(24) NOT NULL, started_at timestamptz NOT NULL, ended_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_onboardings (id text PRIMARY KEY, partner_id text NOT NULL, type varchar(48) NOT NULL, status varchar(32) NOT NULL, owner_id text NOT NULL, blocking_finding_ids jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_due_diligence (id text PRIMARY KEY, partner_id text NOT NULL, type varchar(48) NOT NULL, status varchar(24) NOT NULL, source_snapshot jsonb NOT NULL, reviewed_by text, reviewed_at timestamptz, next_review_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_contacts (id text PRIMARY KEY, partner_id text NOT NULL, person_reference text NOT NULL, role varchar(48) NOT NULL, status varchar(24) NOT NULL, primary_for jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_capabilities (id text PRIMARY KEY, partner_id text NOT NULL, code varchar(96) NOT NULL, domain varchar(48) NOT NULL, status varchar(24) NOT NULL, conditions jsonb NOT NULL, source_snapshot jsonb NOT NULL, verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_jurisdictions (id text PRIMARY KEY, partner_id text NOT NULL, country varchar(2) NOT NULL, state varchar(64), county varchar(128), scope_type varchar(24) NOT NULL, status varchar(24) NOT NULL, source_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_agreements (id text PRIMARY KEY, partner_id text NOT NULL, type varchar(48) NOT NULL, code varchar(96) NOT NULL, version integer NOT NULL CHECK(version > 0), status varchar(24) NOT NULL, source_snapshot jsonb NOT NULL, effective_from timestamptz, effective_to timestamptz, commercial_terms_reference text, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(code, version));
CREATE TABLE public.partner_authorizations (id text PRIMARY KEY, partner_id text NOT NULL, type varchar(48) NOT NULL, capability_id text, jurisdiction_id text, agreement_id text, status varchar(24) NOT NULL, source_snapshot jsonb NOT NULL, approved_by text, effective_from timestamptz, effective_to timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_documents (id text PRIMARY KEY, partner_id text NOT NULL, document_type varchar(48) NOT NULL, document_reference text NOT NULL, status varchar(24) NOT NULL, expires_at timestamptz, source_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_assignments (id text PRIMARY KEY, partner_id text NOT NULL, source_module varchar(8) NOT NULL, source_resource_id text NOT NULL, status varchar(24) NOT NULL, idempotency_key varchar(160) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_economics (id text PRIMARY KEY, partner_id text NOT NULL, agreement_id text NOT NULL, qualifying_event_reference text NOT NULL, status varchar(24) NOT NULL, amount_cents integer, currency varchar(3) NOT NULL, source_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.partner_findings (id text PRIMARY KEY, partner_id text NOT NULL, type varchar(48) NOT NULL, severity varchar(16) NOT NULL, status varchar(32) NOT NULL, blocking boolean NOT NULL DEFAULT false, source_snapshot jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_capabilities ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_jurisdictions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_agreements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_authorizations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_assignments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_economics ENABLE ROW LEVEL SECURITY; ALTER TABLE public.partner_findings ENABLE ROW LEVEL SECURITY;
CREATE POLICY partner_gateway_deny_direct_partner ON public.partners AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false); CREATE POLICY partner_gateway_deny_direct_assignments ON public.partner_assignments AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false); CREATE POLICY partner_gateway_deny_direct_economics ON public.partner_economics AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false);