-- M041 Provider Abstraction controlled foundation. Authored only; never executed.
CREATE ROLE atlas_provider_gateway NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT; ALTER ROLE atlas_provider_gateway NOBYPASSRLS;
CREATE TABLE public.provider_definitions (id text PRIMARY KEY, code varchar(96) NOT NULL UNIQUE, display_name varchar(256) NOT NULL, category varchar(64) NOT NULL, organization_id text, partner_id text, ownership_type varchar(32) NOT NULL, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_interfaces (id text PRIMARY KEY, code varchar(96) NOT NULL, version integer NOT NULL CHECK(version > 0), domain varchar(64) NOT NULL, status varchar(24) NOT NULL, schema_version varchar(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(), UNIQUE(code, version));
CREATE TABLE public.provider_capability_definitions (id text PRIMARY KEY, code varchar(128) NOT NULL UNIQUE, interface_id text NOT NULL, request_schema_id text NOT NULL, response_schema_id text NOT NULL, status varchar(24) NOT NULL, data_minimization jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_capabilities (id text PRIMARY KEY, provider_id text NOT NULL, capability_code varchar(128) NOT NULL, support_status varchar(24) NOT NULL, adapter_version varchar(64) NOT NULL, constraints jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_schemas (id text PRIMARY KEY, provider_id text, interface_id text NOT NULL, schema_type varchar(32) NOT NULL, version varchar(64) NOT NULL, content_hash varchar(128) NOT NULL, compatibility varchar(32) NOT NULL, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_adapters (id text PRIMARY KEY, provider_id text NOT NULL, interface_id text NOT NULL, adapter_code varchar(128) NOT NULL, adapter_version varchar(64) NOT NULL, runtime varchar(24) NOT NULL, status varchar(24) NOT NULL, configuration_profile_id text, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_configurations (id text PRIMARY KEY, provider_id text NOT NULL, environment varchar(16) NOT NULL, region varchar(64), configuration jsonb NOT NULL, secret_references jsonb NOT NULL, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_endpoints (id text PRIMARY KEY, provider_id text NOT NULL, environment varchar(16) NOT NULL, endpoint_type varchar(24) NOT NULL, base_url text NOT NULL, status varchar(24) NOT NULL, verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_requests (id text PRIMARY KEY, provider_id text NOT NULL, capability_code varchar(128) NOT NULL, adapter_version varchar(64) NOT NULL, environment varchar(16) NOT NULL, correlation_id varchar(160) NOT NULL, source_module varchar(16) NOT NULL, source_resource_id text NOT NULL, request_hash varchar(128) NOT NULL, idempotency_key varchar(160) NOT NULL UNIQUE, canonical_status varchar(32) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_responses (id text PRIMARY KEY, provider_request_id text NOT NULL, provider_reference text, raw_status varchar(128), raw_code varchar(128), canonical_status varchar(32) NOT NULL, response_schema_version varchar(64) NOT NULL, payload_reference text, received_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_health (id text PRIMARY KEY, provider_id text NOT NULL, capability_code varchar(128) NOT NULL, environment varchar(16) NOT NULL, status varchar(24) NOT NULL, observed_at timestamptz NOT NULL, source varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_routes (id text PRIMARY KEY, capability_code varchar(128) NOT NULL, environment varchar(16) NOT NULL, provider_id text NOT NULL, priority integer NOT NULL, status varchar(24) NOT NULL, sticky boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
CREATE TABLE public.provider_findings (id text PRIMARY KEY, provider_id text NOT NULL, type varchar(64) NOT NULL, severity varchar(16) NOT NULL, blocking boolean NOT NULL DEFAULT false, status varchar(24) NOT NULL, created_at timestamptz NOT NULL DEFAULT transaction_timestamp(), updated_at timestamptz NOT NULL DEFAULT transaction_timestamp());
ALTER TABLE public.provider_definitions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.provider_configurations ENABLE ROW LEVEL SECURITY; ALTER TABLE public.provider_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.provider_responses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.provider_findings ENABLE ROW LEVEL SECURITY;
CREATE POLICY provider_gateway_deny_direct_provider ON public.provider_definitions AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false); CREATE POLICY provider_gateway_deny_direct_config ON public.provider_configurations AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false); CREATE POLICY provider_gateway_deny_direct_requests ON public.provider_requests AS RESTRICTIVE FOR ALL TO PUBLIC USING (false) WITH CHECK (false);