export const BUSINESS_ROADMAP_MODULE = "M101" as const;
export const BUSINESS_ROADMAP_PERMISSIONS = ["business_roadmap.create", "business_roadmap.version.manage", "business_roadmap.wave.manage", "business_roadmap.experiment.manage", "business_roadmap.capacity.manage", "business_roadmap.decision_gate.manage", "business_roadmap.review.request", "business_roadmap.runtime.activate"] as const;
export type BusinessRoadmapPermission = (typeof BUSINESS_ROADMAP_PERMISSIONS)[number];
export const BUSINESS_ROADMAP_RUNTIME = { marketResearchConnections: false, kpiAggregation: false, crmAccess: false, campaignActivation: false, commercialOfferChanges: false, priceChanges: false, partnerActivation: false, paymentActions: false, automaticExecution: false } as const;
export type BusinessWaveCode = "WAVE_0" | "WAVE_1" | "WAVE_2" | "WAVE_3" | "WAVE_4" | "WAVE_5" | "WAVE_6" | "WAVE_7" | "WAVE_8" | "WAVE_9";
export type BusinessEvidenceStatus = "unvalidated" | "unknown" | "review_required";

export interface BusinessRoadmap { readonly module: typeof BUSINESS_ROADMAP_MODULE; readonly code: string; readonly title: string; readonly status: "draft"; readonly active: false; readonly commercialExecutionEnabled: false; readonly technicalAuthority: false; }
export interface BusinessRoadmapVersion { readonly code: string; readonly roadmapCode: string; readonly versionNumber: number; readonly changeSummary: string; readonly status: "draft"; readonly immutable: false; readonly approved: false; }
export interface BusinessExecutionWave { readonly code: BusinessWaveCode; readonly roadmapVersionCode: string; readonly objectiveReference: string; readonly segmentFocusReferences: readonly string[]; readonly offerFocusReferences: readonly string[]; readonly readinessGateReferences: readonly string[]; readonly kpiReferences: readonly string[]; readonly status: "not_started"; readonly entryGatePassed: false; readonly exitGatePassed: false; readonly commercialActivationStarted: false; }
export interface BusinessSegmentHypothesis { readonly code: string; readonly roadmapVersionCode: string; readonly segmentReference: string; readonly problemReference: string; readonly evidenceReferences: readonly string[]; readonly evidenceStatus: BusinessEvidenceStatus; readonly targetingActivated: false; readonly outcomeClaimed: false; }
export interface BusinessOfferReadiness { readonly code: string; readonly roadmapVersionCode: string; readonly catalogReference: string; readonly operationalReadinessReference: string; readonly complianceReadinessReference: string; readonly technicalReadinessReference: string; readonly status: "not_ready"; readonly publicSaleEnabled: false; readonly pricingChanged: false; }
export interface BusinessKpiDefinition { readonly code: string; readonly roadmapVersionCode: string; readonly metricReference: string; readonly intendedUse: "learning" | "capacity" | "quality" | "economics" | "risk"; readonly evidenceReferences: readonly string[]; readonly status: "unmeasured"; readonly dataQueryExecuted: false; readonly outcomeClaimed: false; }
export interface BusinessCapacityConstraint { readonly code: string; readonly roadmapVersionCode: string; readonly serviceReference: string; readonly type: "staffing" | "quality" | "support" | "provider" | "cash_flow" | "technical" | "unknown"; readonly evidenceReferences: readonly string[]; readonly status: "unverified"; readonly scalingAuthorized: false; }
export interface BusinessExperiment { readonly code: string; readonly roadmapVersionCode: string; readonly hypothesisReference: string; readonly channelReference: string; readonly successMetricReferences: readonly string[]; readonly stopConditionReferences: readonly string[]; readonly status: "draft"; readonly activated: false; readonly leadDataCollected: false; readonly outcomeClaimed: false; }
export interface BusinessDecisionGate { readonly code: string; readonly roadmapVersionCode: string; readonly decisionReference: string; readonly affectedWaveReferences: readonly string[]; readonly status: "pending_product_owner_decision"; readonly decisionRecorded: false; readonly commercialActionAuthorized: false; }
export interface BusinessContinuityPlan { readonly code: string; readonly roadmapVersionCode: string; readonly criticalProcessReferences: readonly string[]; readonly providerAlternativeReferences: readonly string[]; readonly ownerCoverageReferences: readonly string[]; readonly status: "draft"; readonly exercised: false; readonly businessContinuityGuaranteed: false; }
export interface BusinessReviewRequest { readonly code: string; readonly roadmapVersionCode: string; readonly evidenceReferences: readonly string[]; readonly status: "review_required"; readonly reviewPerformed: false; readonly commercialActionStarted: false; }

function permit(value: BusinessRoadmapPermission): void { if (!BUSINESS_ROADMAP_PERMISSIONS.includes(value)) throw new Error("Unsupported business roadmap permission."); }
function code(value: string, field: string): void { if (!/^[A-Z][A-Z0-9_:-]{2,127}$/u.test(value)) throw new Error(`${field} must be a stable safe identifier.`); }
function ref(value: string, field: string): void { if (!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{2,255}$/u.test(value)) throw new Error(`${field} must be a safe reference.`); }
function refs(values: readonly string[], field: string, required = false): readonly string[] { if (required && !values.length) throw new Error(`${field} requires at least one reference.`); for (const value of values) ref(value, field); return [...new Set(values)]; }
function safeText(value: string, field: string): void { if (/(-----BEGIN|authorization:|bearer\s|password\s*=|api[_-]?key\s*=|token\s*=|chain[\s-]?of[\s-]?thought)/iu.test(value)) throw new Error(`${field} cannot contain credentials or private reasoning.`); }

export function createBusinessRoadmap(input: { permission: BusinessRoadmapPermission; code: string; title: string }): BusinessRoadmap { permit(input.permission); code(input.code, "Business roadmap code"); safeText(input.title, "Business roadmap title"); return { module: BUSINESS_ROADMAP_MODULE, code: input.code, title: input.title, status: "draft", active: false, commercialExecutionEnabled: false, technicalAuthority: false }; }
export function createBusinessRoadmapVersion(input: { permission: BusinessRoadmapPermission; code: string; roadmap: BusinessRoadmap; versionNumber: number; changeSummary: string }): BusinessRoadmapVersion { permit(input.permission); code(input.code, "Business roadmap version code"); if (!Number.isSafeInteger(input.versionNumber) || input.versionNumber < 1) throw new Error("Roadmap version must be a positive integer."); safeText(input.changeSummary, "Business roadmap change summary"); return { code: input.code, roadmapCode: input.roadmap.code, versionNumber: input.versionNumber, changeSummary: input.changeSummary, status: "draft", immutable: false, approved: false }; }
export function createBusinessExecutionWave(input: { permission: BusinessRoadmapPermission; code: BusinessWaveCode; version: BusinessRoadmapVersion; objectiveReference: string; segmentFocusReferences?: readonly string[]; offerFocusReferences?: readonly string[]; readinessGateReferences: readonly string[]; kpiReferences: readonly string[] }): BusinessExecutionWave { permit(input.permission); ref(input.objectiveReference, "Business wave objective reference"); return { code: input.code, roadmapVersionCode: input.version.code, objectiveReference: input.objectiveReference, segmentFocusReferences: refs(input.segmentFocusReferences ?? [], "Segment focus references"), offerFocusReferences: refs(input.offerFocusReferences ?? [], "Offer focus references"), readinessGateReferences: refs(input.readinessGateReferences, "Readiness gate references", true), kpiReferences: refs(input.kpiReferences, "KPI references", true), status: "not_started", entryGatePassed: false, exitGatePassed: false, commercialActivationStarted: false }; }
export function createBusinessSegmentHypothesis(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; segmentReference: string; problemReference: string; evidenceReferences?: readonly string[] }): BusinessSegmentHypothesis { permit(input.permission); code(input.code, "Business segment hypothesis code"); ref(input.segmentReference, "Segment reference"); ref(input.problemReference, "Problem reference"); return { code: input.code, roadmapVersionCode: input.version.code, segmentReference: input.segmentReference, problemReference: input.problemReference, evidenceReferences: refs(input.evidenceReferences ?? [], "Segment evidence references"), evidenceStatus: "unvalidated", targetingActivated: false, outcomeClaimed: false }; }
export function createBusinessOfferReadiness(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; catalogReference: string; operationalReadinessReference: string; complianceReadinessReference: string; technicalReadinessReference: string }): BusinessOfferReadiness { permit(input.permission); code(input.code, "Business offer readiness code"); ref(input.catalogReference, "Catalog reference"); ref(input.operationalReadinessReference, "Operational readiness reference"); ref(input.complianceReadinessReference, "Compliance readiness reference"); ref(input.technicalReadinessReference, "Technical readiness reference"); return { code: input.code, roadmapVersionCode: input.version.code, catalogReference: input.catalogReference, operationalReadinessReference: input.operationalReadinessReference, complianceReadinessReference: input.complianceReadinessReference, technicalReadinessReference: input.technicalReadinessReference, status: "not_ready", publicSaleEnabled: false, pricingChanged: false }; }
export function defineBusinessKpi(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; metricReference: string; intendedUse: BusinessKpiDefinition["intendedUse"]; evidenceReferences?: readonly string[] }): BusinessKpiDefinition { permit(input.permission); code(input.code, "Business KPI code"); ref(input.metricReference, "Metric reference"); return { code: input.code, roadmapVersionCode: input.version.code, metricReference: input.metricReference, intendedUse: input.intendedUse, evidenceReferences: refs(input.evidenceReferences ?? [], "KPI evidence references"), status: "unmeasured", dataQueryExecuted: false, outcomeClaimed: false }; }
export function createBusinessCapacityConstraint(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; serviceReference: string; type: BusinessCapacityConstraint["type"]; evidenceReferences?: readonly string[] }): BusinessCapacityConstraint { permit(input.permission); code(input.code, "Business capacity constraint code"); ref(input.serviceReference, "Service reference"); return { code: input.code, roadmapVersionCode: input.version.code, serviceReference: input.serviceReference, type: input.type, evidenceReferences: refs(input.evidenceReferences ?? [], "Capacity evidence references"), status: "unverified", scalingAuthorized: false }; }
export function createBusinessExperiment(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; hypothesisReference: string; channelReference: string; successMetricReferences: readonly string[]; stopConditionReferences: readonly string[] }): BusinessExperiment { permit(input.permission); code(input.code, "Business experiment code"); ref(input.hypothesisReference, "Hypothesis reference"); ref(input.channelReference, "Channel reference"); return { code: input.code, roadmapVersionCode: input.version.code, hypothesisReference: input.hypothesisReference, channelReference: input.channelReference, successMetricReferences: refs(input.successMetricReferences, "Success metric references", true), stopConditionReferences: refs(input.stopConditionReferences, "Stop condition references", true), status: "draft", activated: false, leadDataCollected: false, outcomeClaimed: false }; }
export function createBusinessDecisionGate(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; decisionReference: string; affectedWaveReferences: readonly string[] }): BusinessDecisionGate { permit(input.permission); code(input.code, "Business decision gate code"); ref(input.decisionReference, "Decision reference"); return { code: input.code, roadmapVersionCode: input.version.code, decisionReference: input.decisionReference, affectedWaveReferences: refs(input.affectedWaveReferences, "Affected wave references", true), status: "pending_product_owner_decision", decisionRecorded: false, commercialActionAuthorized: false }; }
export function createBusinessContinuityPlan(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; criticalProcessReferences: readonly string[]; providerAlternativeReferences?: readonly string[]; ownerCoverageReferences: readonly string[] }): BusinessContinuityPlan { permit(input.permission); code(input.code, "Business continuity plan code"); return { code: input.code, roadmapVersionCode: input.version.code, criticalProcessReferences: refs(input.criticalProcessReferences, "Critical process references", true), providerAlternativeReferences: refs(input.providerAlternativeReferences ?? [], "Provider alternative references"), ownerCoverageReferences: refs(input.ownerCoverageReferences, "Owner coverage references", true), status: "draft", exercised: false, businessContinuityGuaranteed: false }; }
export function requestBusinessReview(input: { permission: BusinessRoadmapPermission; code: string; version: BusinessRoadmapVersion; evidenceReferences?: readonly string[] }): BusinessReviewRequest { permit(input.permission); code(input.code, "Business review request code"); return { code: input.code, roadmapVersionCode: input.version.code, evidenceReferences: refs(input.evidenceReferences ?? [], "Review evidence references"), status: "review_required", reviewPerformed: false, commercialActionStarted: false }; }