import type { HelpCategoryId, KnowledgeRecord } from "../../domain/help-center";

interface FaqSeed {
  key: string;
  category: HelpCategoryId;
  es: { question: string; answer: string; keywords: string[] };
  en: { question: string; answer: string; keywords: string[] };
}

const FAQ_SEEDS: FaqSeed[] = [
  faq("what-is-sg", "getting-started", "¿Qué es SG Solutions?", "SG Solutions ofrece orientación y servicios para organizar necesidades de crédito, taxes, formación empresarial, financiamiento y preparación para comprar casa. Cada servicio comienza aclarando alcance y próximos pasos.", ["empresa", "servicios"], "What is SG Solutions?", "SG Solutions provides guidance and services for organizing credit, tax, business formation, funding and home-buying preparation needs. Each service starts by clarifying scope and next steps.", ["company", "services"]),
  faq("services-offered", "getting-started", "¿Qué servicios ofrecen?", "El sitio presenta las áreas disponibles y sus límites. La oferta incluye preparación y acompañamiento; la disponibilidad exacta se confirma durante una evaluación, sin prometer resultados.", ["servicios", "áreas"], "What services do you offer?", "The website explains the available service areas and their boundaries. The offering includes preparation and support; exact availability is confirmed during an evaluation without promising outcomes.", ["services", "areas"]),
  faq("spanish-support", "getting-started", "¿Atienden en español?", "Sí. La experiencia pública está disponible en español e inglés. La disponibilidad de una persona y del material especializado se confirma al coordinar el siguiente paso.", ["español", "idioma"], "Do you provide service in Spanish?", "Yes. The public experience is available in Spanish and English. Availability of a person and specialized materials is confirmed when the next step is coordinated.", ["Spanish", "language"]),
  faq("how-to-start", "getting-started", "¿Cómo comienzo?", "Explora el servicio que te interesa y agenda una evaluación cuando el canal esté activo. La evaluación ayuda a aclarar el objetivo, la información necesaria y el próximo paso.", ["comenzar", "evaluación"], "How do I get started?", "Explore the service you are interested in and schedule an evaluation when that channel is active. The evaluation helps clarify your goal, required information and next step.", ["start", "evaluation"]),
  faq("account-required", "getting-started", "¿Necesito crear una cuenta?", "No para explorar servicios o información pública. La cuenta se crea cuando corresponde dentro del proceso comercial y nunca es el primer requisito para entender la oferta.", ["cuenta", "portal"], "Do I need to create an account?", "Not to explore services or public information. An account is created when appropriate in the commercial process and is never the first requirement for understanding the offering.", ["account", "portal"]),
  faq("schedule-appointment", "getting-started", "¿Cómo agendo una cita?", "Usa la acción de evaluación cuando el sistema de citas esté activado. Si todavía no está disponible, el sitio lo indica claramente y no afirma que una cita fue reservada.", ["cita", "agenda"], "How do I schedule an appointment?", "Use the evaluation action when scheduling is activated. If it is not yet available, the website states that clearly and does not claim an appointment was booked.", ["appointment", "schedule"]),
  faq("contact-person", "getting-started", "¿Cómo contacto a una persona?", "La página de contacto mostrará únicamente canales verificados y aprobados. Si un canal todavía no está activo, puedes revisar los servicios y volver cuando aparezca una opción segura.", ["contacto", "persona"], "How do I contact a person?", "The contact page displays only verified and approved channels. If a channel is not active yet, you can review services and return when a secure option appears.", ["contact", "person"]),

  faq("how-to-pay", "payments", "¿Cómo pago?", "Cuando corresponda, SG Solutions enviará o mostrará un enlace seguro de Stripe asociado al servicio o cotización. No envíes números de tarjeta por chat, email o formularios públicos.", ["pago", "Stripe"], "How do I pay?", "When appropriate, SG Solutions will send or display a secure Stripe link associated with the service or quote. Do not send card numbers through chat, email or public forms.", ["payment", "Stripe"]),
  faq("payment-methods", "payments", "¿Qué métodos aceptan?", "Los métodos disponibles aparecerán directamente en el checkout seguro cuando se active. SG Solutions no publica una lista definitiva hasta que Stripe y la oferta aplicable la confirmen.", ["métodos", "checkout"], "What payment methods do you accept?", "Available methods will appear directly in secure checkout when activated. SG Solutions does not publish a definitive list until Stripe and the applicable offer confirm it.", ["methods", "checkout"]),
  faq("payment-starts-service", "payments", "¿Pagar inicia automáticamente el servicio?", "No. El pago confirmado puede hacer que el servicio sea elegible para comenzar, pero una persona autorizada debe revisar la información y aprobar formalmente el inicio.", ["pago", "inicio"], "Does payment automatically start the service?", "No. A confirmed payment may make the service eligible to begin, but an authorized person must review the information and formally approve the start.", ["payment", "start"]),
  faq("where-is-receipt", "payments", "¿Dónde veo mi recibo?", "Stripe puede emitir un recibo al canal asociado con el pago y, cuando el portal esté activo, el historial aparecerá allí. Conserva únicamente enlaces y mensajes verificados.", ["recibo", "historial"], "Where can I find my receipt?", "Stripe may issue a receipt to the channel associated with the payment and, when the portal is active, the history will appear there. Keep only verified links and messages.", ["receipt", "history"]),
  faq("request-refund", "payments", "¿Cómo solicito un reembolso?", "Los reembolsos no son automáticos. La solicitud se revisa según el servicio, el trabajo realizado y los términos aplicables; usa únicamente el canal seguro indicado en tu documentación.", ["reembolso", "términos"], "How do I request a refund?", "Refunds are not automatic. A request is reviewed according to the service, work performed and applicable terms; use only the secure channel identified in your documentation.", ["refund", "terms"]),
  faq("payment-failed", "payments", "¿Qué sucede si el pago falla?", "El servicio no se marca como pagado ni se autoriza automáticamente. Revisa el mensaje de Stripe, evita repetir intentos innecesarios y solicita ayuda mediante un canal verificado si continúa el problema.", ["pago fallido", "Stripe"], "What happens if a payment fails?", "The service is not marked paid or automatically authorized. Review the Stripe message, avoid unnecessary repeated attempts and request help through a verified channel if the issue continues.", ["failed payment", "Stripe"]),

  faq("upload-documents", "documents", "¿Cómo subo documentos?", "Los documentos sensibles se enviarán únicamente mediante el portal privado cuando esté habilitado. El sitio público no acepta reportes, identificaciones, formularios fiscales ni información bancaria.", ["subir", "portal"], "How do I upload documents?", "Sensitive documents will be sent only through the private portal when enabled. The public website does not accept reports, identification, tax forms or banking information.", ["upload", "portal"]),
  faq("document-formats", "documents", "¿Qué formatos aceptan?", "El portal seguro mostrará los formatos y límites autorizados para cada solicitud. No cambies la extensión de un archivo para intentar enviarlo y nunca cargues ejecutables o archivos desconocidos.", ["formatos", "archivos"], "What file formats do you accept?", "The secure portal will show authorized formats and limits for each request. Do not rename a file extension to force an upload and never upload executables or unknown files.", ["formats", "files"]),
  faq("protect-information", "documents", "¿Cómo protegen mi información?", "SG Solutions aplica acceso por función y expediente, almacenamiento privado y registros de auditoría. La información sensible no debe enviarse por canales públicos o enlaces no verificados.", ["seguridad", "privacidad"], "How do you protect my information?", "SG Solutions applies role- and case-based access, private storage and audit records. Sensitive information should not be sent through public channels or unverified links.", ["security", "privacy"]),
  faq("document-received", "documents", "¿Cómo sé si recibieron un documento?", "Cuando el portal esté activo, cada carga aceptada mostrará un estado de recepción. Un archivo enviado por un canal no autorizado no debe considerarse recibido ni procesado.", ["recibido", "estado"], "How do I know whether a document was received?", "When the portal is active, each accepted upload will show a received status. A file sent through an unauthorized channel should not be considered received or processed.", ["received", "status"]),
  faq("delete-document", "documents", "¿Puedo eliminar un documento?", "La eliminación depende del estado del expediente, las obligaciones de retención y cualquier restricción aplicable. Solicitarla no significa que el archivo pueda eliminarse de inmediato.", ["eliminar", "retención"], "Can I delete a document?", "Deletion depends on case status, retention obligations and any applicable restriction. Requesting deletion does not mean the file can be removed immediately.", ["delete", "retention"]),

  faq("remove-any-negative", "credit", "¿Pueden eliminar cualquier cuenta negativa?", "No. La información exacta y verificable no se elimina solo por ser negativa. Una revisión puede identificar información que requiere investigación, pero el resultado depende de la evidencia y de terceros.", ["cuenta negativa", "disputa"], "Can you remove any negative account?", "No. Accurate, verifiable information is not removed merely because it is negative. A review may identify information that requires investigation, but the outcome depends on evidence and third parties.", ["negative account", "dispute"]),
  faq("score-guarantee", "credit", "¿Garantizan aumento del score?", "No. Los modelos, reportes y decisiones de terceros cambian y ningún resultado específico puede prometerse. SG Solutions puede ayudar a organizar información y próximos pasos permitidos.", ["score", "resultado"], "Do you guarantee a score increase?", "No. Models, reports and third-party decisions change, so no specific outcome can be promised. SG Solutions can help organize information and permitted next steps.", ["score", "outcome"]),
  faq("what-is-dispute", "credit", "¿Qué es una disputa?", "Es una solicitud para que una entidad investigue información que una persona considera inexacta o incompleta. No es una promesa de eliminación y debe basarse en información verdadera y evidencia disponible.", ["disputa", "investigación"], "What is a dispute?", "It is a request for an entity to investigate information a person believes is inaccurate or incomplete. It is not a promise of deletion and must rely on truthful information and available evidence.", ["dispute", "investigation"]),
  faq("what-is-utilization", "credit", "¿Qué es utilización?", "Es una relación entre saldos reportados y límites disponibles en cuentas de crédito revolvente. Es solo uno de varios factores que pueden influir en distintos modelos.", ["utilización", "saldo"], "What is utilization?", "It is a relationship between reported balances and available limits on revolving credit accounts. It is only one of several factors that may influence different models.", ["utilization", "balance"]),
  faq("credit-report-needed", "credit", "¿Necesito un reporte?", "Una revisión responsable suele requerir información actual y autorizada. SG Solutions indicará qué fuente o documento es necesario y no debe recibir credenciales por canales públicos.", ["reporte", "autorización"], "Do I need a credit report?", "A responsible review usually requires current, authorized information. SG Solutions will identify the needed source or document and should not receive credentials through public channels.", ["report", "authorization"]),
  faq("what-is-identityiq", "credit", "¿Qué es IdentityIQ?", "Es un proveedor externo de monitoreo de identidad y crédito. Cualquier conexión futura requiere autorización, consentimiento y revisión de sus términos; SG Solutions no controla sus reportes ni disponibilidad.", ["IdentityIQ", "monitoreo"], "What is IdentityIQ?", "It is an external identity and credit monitoring provider. Any future connection requires authorization, consent and review of its terms; SG Solutions does not control its reports or availability.", ["IdentityIQ", "monitoring"]),
  faq("what-is-tradeline", "credit", "¿Qué es una tradeline?", "Es el registro de una cuenta de crédito en un reporte. Los productos de terceros relacionados con tradelines no garantizan un resultado, aprobación o cambio específico.", ["tradeline", "reporte"], "What is a tradeline?", "It is the record of a credit account on a report. Third-party products related to tradelines do not guarantee a particular outcome, approval or change.", ["tradeline", "report"]),

  faq("tax-documents", "taxes", "¿Qué documentos necesito?", "Depende del año y de tus fuentes de ingreso, gastos, dependientes y créditos. Una evaluación identifica la lista aplicable; no envíes documentos fiscales por el sitio público.", ["documentos", "taxes"], "What documents do I need?", "It depends on the year and your sources of income, expenses, dependents and credits. An evaluation identifies the applicable list; do not send tax documents through the public website.", ["documents", "taxes"]),
  faq("w2-1099", "taxes", "¿Trabajan con W-2 y 1099?", "SG Solutions contempla preparación relacionada con distintos tipos de ingresos, pero el alcance se confirma después de revisar el año fiscal y los documentos disponibles.", ["W-2", "1099"], "Do you work with W-2 and 1099 forms?", "SG Solutions considers preparation involving different income types, but scope is confirmed after reviewing the tax year and available documents.", ["W-2", "1099"]),
  faq("schedule-c", "taxes", "¿Preparan Schedule C?", "La preparación para trabajo independiente puede incluir Schedule C cuando corresponda. Primero se revisan ingresos, gastos, registros y el alcance autorizado para ese año.", ["Schedule C", "negocio"], "Do you prepare Schedule C?", "Self-employment preparation may include Schedule C when appropriate. Income, expenses, records and the authorized scope for that year are reviewed first.", ["Schedule C", "business"]),
  faq("refund-guarantee", "taxes", "¿Garantizan refund?", "No. Un reembolso depende de la información fiscal, las reglas aplicables y la determinación de la autoridad tributaria. SG Solutions no promete un monto ni un resultado.", ["refund", "resultado"], "Do you guarantee a refund?", "No. A refund depends on tax information, applicable rules and the tax authority's determination. SG Solutions does not promise an amount or outcome.", ["refund", "outcome"]),
  faq("tax-signature", "taxes", "¿Cómo firmo?", "Cuando la firma electrónica esté habilitada, recibirás una solicitud mediante el canal aprobado. Verifica la identidad del remitente y revisa el documento antes de firmar.", ["firma", "electrónica"], "How do I sign?", "When electronic signature is enabled, you will receive a request through the approved channel. Verify the sender and review the document before signing.", ["signature", "electronic"]),
  faq("return-accepted", "taxes", "¿Cómo sé si mi return fue aceptado?", "La presentación y su estado deben confirmarse mediante la autoridad o proveedor autorizado. Un pago a SG Solutions no demuestra que una declaración fue presentada o aceptada.", ["aceptación", "presentación"], "How do I know whether my return was accepted?", "Filing and status must be confirmed through the authorized authority or provider. A payment to SG Solutions does not prove that a return was filed or accepted.", ["acceptance", "filing"]),

  faq("what-is-llc", "business-formation", "¿Qué es una LLC?", "Es una forma de entidad empresarial creada bajo la ley estatal. Su conveniencia depende de objetivos, operación, impuestos y jurisdicción; la información general no sustituye asesoría individual.", ["LLC", "entidad"], "What is an LLC?", "It is a form of business entity created under state law. Whether it fits depends on goals, operations, taxes and jurisdiction; general information does not replace individual advice.", ["LLC", "entity"]),
  faq("registered-agent", "business-formation", "¿Qué es un registered agent?", "Es la persona o entidad designada para recibir ciertas comunicaciones oficiales de una empresa. Los requisitos y disponibilidad dependen del estado y del servicio contratado.", ["registered agent", "estado"], "What is a registered agent?", "It is the person or entity designated to receive certain official communications for a business. Requirements and availability depend on the state and purchased service.", ["registered agent", "state"]),
  faq("what-is-ein", "business-formation", "¿Qué es un EIN?", "Es un número de identificación asignado por el IRS a determinadas entidades o actividades. Obtenerlo no crea por sí solo una empresa ni sustituye los filings estatales necesarios.", ["EIN", "IRS"], "What is an EIN?", "It is an identification number assigned by the IRS to certain entities or activities. Obtaining it does not by itself create a business or replace required state filings.", ["EIN", "IRS"]),
  faq("formation-time", "business-formation", "¿Cuánto tarda?", "El tiempo depende del estado, el tipo de entidad, la información completa y el procesamiento de terceros. SG Solutions confirma el estado, pero no promete una fecha antes de revisar el caso.", ["tiempo", "filing"], "How long does it take?", "Timing depends on the state, entity type, complete information and third-party processing. SG Solutions confirms status but does not promise a date before reviewing the case.", ["timing", "filing"]),
  faq("state-fee", "business-formation", "¿El precio incluye la tarifa estatal?", "No debe asumirse. La cotización o acuerdo indicará por separado qué honorarios y tarifas gubernamentales están incluidos antes de cualquier pago.", ["tarifa estatal", "precio"], "Does the price include the state fee?", "Do not assume that it does. The quote or agreement will separately state which professional fees and government charges are included before payment.", ["state fee", "price"]),
  faq("payment-files-immediately", "business-formation", "¿Pagar significa que se presenta inmediatamente?", "No. El pago no reemplaza la revisión de nombre, datos, documentos, consentimiento ni aprobación humana. El filing ocurre solo después de completar los controles aplicables.", ["pago", "filing"], "Does payment mean the filing happens immediately?", "No. Payment does not replace review of the name, data, documents, consent or human approval. Filing occurs only after applicable checks are complete.", ["payment", "filing"]),
  faq("operating-agreement", "business-formation", "¿Necesito operating agreement?", "Depende de la entidad, propietarios, estado y necesidades operativas. SG Solutions puede explicar el proceso general, pero la decisión y el contenido requieren revisión adecuada.", ["operating agreement", "miembros"], "Do I need an operating agreement?", "It depends on the entity, owners, state and operational needs. SG Solutions can explain the general process, but the decision and content require appropriate review.", ["operating agreement", "members"]),

  faq("funding-guarantee", "business-funding", "¿Garantizan aprobación?", "No. Los prestamistas y proveedores deciden según sus propios criterios y la información del solicitante. SG Solutions ayuda con preparación y opciones, no garantiza decisiones de terceros.", ["aprobación", "lender"], "Do you guarantee approval?", "No. Lenders and providers decide under their own criteria and the applicant's information. SG Solutions helps with preparation and options but does not guarantee third-party decisions.", ["approval", "lender"]),
  faq("fundability", "business-funding", "¿Qué es fundability?", "Es una manera general de describir qué tan preparada parece una empresa para una evaluación de financiamiento, considerando estructura, registros, flujo de caja, crédito y documentación.", ["fundability", "preparación"], "What is fundability?", "It is a general way to describe how prepared a business appears for a funding review, considering structure, records, cash flow, credit and documentation.", ["fundability", "preparation"]),
  faq("funding-documents", "business-funding", "¿Qué documentos necesito?", "La lista depende del producto y proveedor. Puede incluir información empresarial, identificación, estados, ingresos y obligaciones; solo se solicita mediante un flujo seguro y autorizado.", ["documentos", "funding"], "What documents do I need?", "The list depends on the product and provider. It may include business information, identification, statements, income and obligations; it is requested only through a secure, authorized flow.", ["documents", "funding"]),
  faq("what-is-sba", "business-funding", "¿Qué es SBA?", "La U.S. Small Business Administration es una agencia federal que apoya a pequeñas empresas y participa en programas con prestamistas. SG Solutions no es la SBA ni decide elegibilidad.", ["SBA", "préstamo"], "What is the SBA?", "The U.S. Small Business Administration is a federal agency that supports small businesses and participates in programs with lenders. SG Solutions is not the SBA and does not decide eligibility.", ["SBA", "loan"]),
  faq("what-is-dscr", "business-funding", "¿Qué es DSCR?", "Es una relación usada para comparar flujo disponible y obligaciones de deuda. La fórmula y los umbrales dependen del producto y proveedor, por lo que no determina aprobación por sí sola.", ["DSCR", "flujo"], "What is DSCR?", "It is a ratio used to compare available cash flow with debt obligations. The formula and thresholds depend on the product and provider, so it does not determine approval by itself.", ["DSCR", "cash flow"]),
  faq("does-sg-lend", "business-funding", "¿SG Solutions presta dinero?", "SG Solutions ofrece preparación y puede orientar hacia opciones de terceros cuando estén aprobadas. No debe interpretarse como el prestamista de un producto salvo que una divulgación específica lo indique.", ["prestamista", "partner"], "Does SG Solutions lend money?", "SG Solutions provides preparation and may guide clients toward approved third-party options. It should not be treated as a product's lender unless a specific disclosure says otherwise.", ["lender", "partner"]),

  faq("usda-direct", "home-buying", "¿Qué es USDA Direct?", "Es un programa de vivienda administrado directamente por USDA Rural Development para solicitantes y propiedades que cumplan sus requisitos. La elegibilidad solo la determina USDA con información verificada.", ["USDA Direct", "vivienda"], "What is USDA Direct?", "It is a housing program administered directly by USDA Rural Development for applicants and properties that meet its requirements. Only USDA determines eligibility using verified information.", ["USDA Direct", "housing"]),
  faq("usda-guaranteed", "home-buying", "¿Qué es USDA Guaranteed?", "Es un programa en el que préstamos de prestamistas aprobados pueden recibir una garantía de USDA Rural Development. El prestamista y USDA aplican requisitos; SG Solutions no decide aprobación.", ["USDA Guaranteed", "lender"], "What is USDA Guaranteed?", "It is a program in which loans from approved lenders may receive a USDA Rural Development guarantee. The lender and USDA apply requirements; SG Solutions does not decide approval.", ["USDA Guaranteed", "lender"]),
  faq("fha-difference", "home-buying", "¿Qué diferencia hay con FHA?", "USDA y FHA son programas distintos con autoridades, requisitos de propiedad, ingresos, ubicación y financiamiento diferentes. Una comparación responsable requiere el perfil y fuentes vigentes.", ["FHA", "USDA"], "How is it different from FHA?", "USDA and FHA are different programs with different authorities and property, income, location and financing requirements. A responsible comparison requires the profile and current sources.", ["FHA", "USDA"]),
  faq("what-is-dti", "home-buying", "¿Qué es DTI?", "Es una relación entre pagos mensuales de deuda e ingreso mensual bruto. Los prestamistas pueden calcularla y usarla de manera distinta; no determina aprobación por sí sola.", ["DTI", "deuda"], "What is DTI?", "It is a ratio of monthly debt payments to gross monthly income. Lenders may calculate and use it differently; it does not determine approval by itself.", ["DTI", "debt"]),
  faq("rural-eligibility", "home-buying", "¿Qué significa elegibilidad rural?", "Los programas de USDA usan herramientas y reglas oficiales para determinar si una dirección y un solicitante pueden cumplir requisitos. Una descripción informal del área no sustituye esa verificación.", ["rural", "elegibilidad"], "What does rural eligibility mean?", "USDA programs use official tools and rules to determine whether an address and applicant may meet requirements. An informal description of the area does not replace that verification.", ["rural", "eligibility"]),
  faq("home-approval-guarantee", "home-buying", "¿Garantizan aprobación?", "No. Prestamistas, agencias, programas y otras partes toman decisiones con información verificada. SG Solutions puede ayudar a preparar, pero no promete aprobación o condiciones.", ["aprobación", "hipoteca"], "Do you guarantee approval?", "No. Lenders, agencies, programs and other parties make decisions using verified information. SG Solutions can help prepare but does not promise approval or terms.", ["approval", "mortgage"]),
  faq("is-sg-lender", "home-buying", "¿SG Solutions es un lender?", "No debe asumirse. SG Solutions ofrece preparación y asistencia; cualquier prestamista o partner se identifica por separado con sus propias responsabilidades y divulgaciones.", ["lender", "SG Solutions"], "Is SG Solutions a lender?", "Do not assume that it is. SG Solutions provides preparation and assistance; any lender or partner is identified separately with its own responsibilities and disclosures.", ["lender", "SG Solutions"]),
  faq("home-documents", "home-buying", "¿Qué documentos necesito?", "La lista depende del programa y prestamista, y puede abarcar identidad, ingresos, empleo, activos, deudas y propiedad. Los documentos sensibles se solicitan solo en canales seguros.", ["documentos", "casa"], "What documents do I need?", "The list depends on the program and lender and may cover identity, income, employment, assets, debts and property. Sensitive documents are requested only through secure channels.", ["documents", "home"]),

  faq("marketplace-ownership", "marketplace", "¿Los productos son de SG Solutions?", "No necesariamente. El marketplace puede mostrar productos de partners o proveedores externos. Cada oferta debe identificar claramente quién la proporciona y quién toma la decisión.", ["marketplace", "partner"], "Are the products offered by SG Solutions?", "Not necessarily. The marketplace may display products from partners or external providers. Each offer must clearly identify who provides it and who makes the decision.", ["marketplace", "partner"]),
  faq("marketplace-commission", "marketplace", "¿Reciben comisión?", "SG Solutions puede recibir compensación por algunas referencias cuando así se divulgue. Esa posibilidad no convierte una oferta en garantía ni reemplaza una comparación responsable.", ["comisión", "divulgación"], "Do you receive a commission?", "SG Solutions may receive compensation for some referrals when disclosed. That possibility does not turn an offer into a guarantee or replace responsible comparison.", ["commission", "disclosure"]),
  faq("recommendation-guarantee", "marketplace", "¿Una recomendación garantiza aprobación?", "No. La información del marketplace es general y la decisión corresponde al proveedor. Una coincidencia o explicación no significa que el producto sea aprobado o adecuado para todos.", ["recomendación", "aprobación"], "Does a recommendation guarantee approval?", "No. Marketplace information is general and the provider makes the decision. A match or explanation does not mean a product will be approved or is suitable for everyone.", ["recommendation", "approval"]),
  faq("marketplace-data", "marketplace", "¿Cómo protegen mis datos?", "La exploración pública no requiere datos financieros sensibles. Cualquier transferencia futura exige propósito, consentimiento, proveedor identificado y un canal seguro con acceso limitado.", ["datos", "privacidad"], "How do you protect my data?", "Public browsing does not require sensitive financial data. Any future transfer requires a purpose, consent, an identified provider and a secure channel with limited access.", ["data", "privacy"]),
  faq("share-with-partners", "marketplace", "¿Se comparte mi información con partners?", "No por el simple hecho de explorar. Compartir información requiere una acción y consentimiento específico que identifique el partner y el propósito antes de la transmisión.", ["partner", "consentimiento"], "Is my information shared with partners?", "Not merely because you browse. Sharing information requires a specific action and consent that identifies the partner and purpose before transmission.", ["partner", "consent"]),
];

export const HELP_FAQ_CONTENT: KnowledgeRecord[] = FAQ_SEEDS.flatMap((seed) => [
  makeFaqRecord(seed, "es"),
  makeFaqRecord(seed, "en"),
]);

function faq(
  key: string,
  category: HelpCategoryId,
  esQuestion: string,
  esAnswer: string,
  esKeywords: string[],
  enQuestion: string,
  enAnswer: string,
  enKeywords: string[],
): FaqSeed {
  return {
    key,
    category,
    es: { question: esQuestion, answer: esAnswer, keywords: esKeywords },
    en: { question: enQuestion, answer: enAnswer, keywords: enKeywords },
  };
}

function makeFaqRecord(seed: FaqSeed, locale: "es" | "en"): KnowledgeRecord {
  const copy = seed[locale];
  const isSpanish = locale === "es";
  return {
    id: `faq-${seed.key}-${locale}`,
    translationGroupId: `faq-${seed.key}`,
    locale,
    type: "faq",
    category: seed.category,
    slug: seed.key,
    title: copy.question,
    summary: copy.answer,
    blocks: [{ type: "paragraph", text: copy.answer }],
    keywords: [...copy.keywords, isSpanish ? "SG Solutions" : "SG Solutions"],
    audiences: ["public", "ai_public"],
    status: "published",
    version: 1,
    riskLevel: "low",
    reviewedAt: "2026-08-08",
    nextReviewAt: "2027-02-08",
    relatedIds: [],
    disclosure: isSpanish
      ? "Información general; una evaluación individual puede cambiar el alcance y los próximos pasos."
      : "General information; an individual evaluation may change scope and next steps.",
    seoTitle: `${copy.question.replace(/[?¿]/g, "")} | SG Solutions`,
    seoDescription: isSpanish
      ? `Respuesta general de SG Solutions: ${copy.answer}`
      : `General guidance from SG Solutions: ${copy.answer}`,
    readingMinutes: 1,
    publishedAt: "2026-08-08",
  };
}
