export const IDEAS_MODULE = "M102" as const;
export const IDEAS_PERMISSIONS = ["ideas.record.create", "ideas.source.link", "ideas.triage.manage", "ideas.scorecard.manage", "ideas.pack.manage", "ideas.parking.request", "ideas.promotion.request", "ideas.runtime.activate"] as const;
export type IdeasPermission = (typeof IDEAS_PERMISSIONS)[number];
export const IDEAS_RUNTIME = { intakeConnections: false, attachmentAccess: false, externalLinkFetch: false, semanticSimilarity: false, searchIndex: false, ranking: false, workflowAutomation: false, notificationDelivery: false, promotionWrites: false, parkingWrites: false, analytics: false, scheduler: false, providerConnections: false } as const;

export type IdeaSourceType = "manual" | "staff" | "client_feedback" | "research" | "support" | "analytics" | "partner" | "ai_suggestion" | "imported" | "other";
export type IdeaDomain = "product_ux" | "services" | "growth" | "marketplace_partners" | "ai_automation" | "documents_workflow" | "security_compliance" | "data_analytics" | "infrastructure" | "voice_gpu" | "cross_module";
export type IdeaScope = "local" | "module" | "cross_module" | "platform" | "unknown";
export type IdeaDispositionCandidate = "needs_enrichment" | "review_required" | "park_candidate" | "merge_candidate" | "reject_candidate" | "promote_candidate";
export type IdeaPromotionDestination = "technical_roadmap" | "business_roadmap" | "parking_lot" | "research" | "experiment" | "future_module";

export interface IdeasSystem { readonly module: typeof IDEAS_MODULE; readonly code: string; readonly status: "draft"; readonly active: false; readonly runtimeEnabled: false; readonly businessAuthority: false; }
export interface IdeaRecord { readonly code: string; readonly systemCode: string; readonly version: 1; readonly sourceType: IdeaSourceType; readonly domain: IdeaDomain; readonly scope: IdeaScope; readonly title: string; readonly problemReference: string; readonly opportunityReference: string; readonly status: "triage_pending"; readonly duplicateResolved: false; readonly promoted: false; readonly parked: false; }
export interface IdeaAssumption { readonly code: string; readonly ideaCode: string; readonly type: "customer" | "business" | "technical" | "compliance" | "cost" | "dependency" | "unknown"; readonly reference: string; readonly status: "unvalidated"; readonly decisionMade: false; }
export interface IdeaEvidenceLink { readonly code: string; readonly ideaCode: string; readonly evidenceType: "research" | "customer_signal" | "operational" | "technical" | "financial" | "compliance" | "unknown"; readonly reference: string; readonly verificationStatus: "unverified"; readonly sourceFetched: false; }
export interface IdeaScorecard { readonly code: string; readonly ideaCode: string; readonly strategicFit: number; readonly customerValue: number; readonly businessValue: number; readonly feasibility: number; readonly risk: number; readonly status: "candidate"; readonly ranked: false; readonly decisionMade: false; }
export interface IdeaTriage { readonly code: string; readonly ideaCode: string; readonly outcome: IdeaDispositionCandidate; readonly missingContextReferences: readonly string[]; readonly status: "review_required"; readonly dispositionApplied: false; readonly notificationSent: false; }
export interface IdeaPack { readonly code: string; readonly ideaCode: string; readonly domain: IdeaDomain; readonly ownerModuleReferences: readonly string[]; readonly safetyGateReferences: readonly string[]; readonly status: "draft"; readonly handoffExecuted: false; }
export interface IdeaParkingRequest { readonly code: string; readonly ideaCode: string; readonly parkingLotReference: string; readonly reasonReference: string; readonly status: "review_required"; readonly parkingWriteExecuted: false; }
export interface IdeaPromotionRequest { readonly code: string; readonly ideaCode: string; readonly destination: IdeaPromotionDestination; readonly destinationReference: string; readonly precheckReferences: readonly string[]; readonly status: "review_required"; readonly destinationWriteExecuted: false; readonly outcomeKnown: false; }
export interface IdeaReadinessResult { readonly ideaCode: string; readonly ready: false; readonly status: "not_ready"; readonly reasons: readonly string[]; }

function permit(value: IdeasPermission): void { if (!IDEAS_PERMISSIONS.includes(value)) throw new Error("Unsupported ideas permission."); }
function code(value: string, field: string): void { if (!/^[A-Z][A-Z0-9_:-]{2,127}$/u.test(value)) throw new Error(`${field} must be a stable safe identifier.`); }
function ref(value: string, field: string): void { if (!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{2,255}$/u.test(value)) throw new Error(`${field} must be a safe reference.`); }
function refs(values: readonly string[], field: string, required = false): readonly string[] { if (required && !values.length) throw new Error(`${field} requires at least one reference.`); for (const value of values) ref(value, field); return [...new Set(values)]; }
function safeText(value: string, field: string): void { if (!value.trim() || /(-----BEGIN|authorization:|bearer\s|password\s*=|api[_-]?key\s*=|token\s*=|chain[\s-]?of[\s-]?thought)/iu.test(value)) throw new Error(`${field} cannot be empty or contain credentials/private reasoning.`); }
function score(value: number, field: string): void { if (!Number.isSafeInteger(value) || value < 0 || value > 5) throw new Error(`${field} must be an integer from 0 to 5.`); }

export function createIdeasSystem(input: { permission: IdeasPermission; code: string }): IdeasSystem { permit(input.permission); code(input.code, "Ideas system code"); return { module: IDEAS_MODULE, code: input.code, status: "draft", active: false, runtimeEnabled: false, businessAuthority: false }; }
export function captureIdea(input: { permission: IdeasPermission; code: string; system: IdeasSystem; sourceType: IdeaSourceType; domain: IdeaDomain; scope: IdeaScope; title: string; problemReference: string; opportunityReference: string }): IdeaRecord { permit(input.permission); code(input.code, "Idea code"); safeText(input.title, "Idea title"); ref(input.problemReference, "Problem reference"); ref(input.opportunityReference, "Opportunity reference"); return { code: input.code, systemCode: input.system.code, version: 1, sourceType: input.sourceType, domain: input.domain, scope: input.scope, title: input.title, problemReference: input.problemReference, opportunityReference: input.opportunityReference, status: "triage_pending", duplicateResolved: false, promoted: false, parked: false }; }
export function recordIdeaAssumption(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; type: IdeaAssumption["type"]; reference: string }): IdeaAssumption { permit(input.permission); code(input.code, "Idea assumption code"); ref(input.reference, "Assumption reference"); return { code: input.code, ideaCode: input.idea.code, type: input.type, reference: input.reference, status: "unvalidated", decisionMade: false }; }
export function linkIdeaEvidence(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; evidenceType: IdeaEvidenceLink["evidenceType"]; reference: string }): IdeaEvidenceLink { permit(input.permission); code(input.code, "Idea evidence code"); ref(input.reference, "Evidence reference"); return { code: input.code, ideaCode: input.idea.code, evidenceType: input.evidenceType, reference: input.reference, verificationStatus: "unverified", sourceFetched: false }; }
export function createIdeaScorecard(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; strategicFit: number; customerValue: number; businessValue: number; feasibility: number; risk: number }): IdeaScorecard { permit(input.permission); code(input.code, "Idea scorecard code"); score(input.strategicFit, "Strategic fit"); score(input.customerValue, "Customer value"); score(input.businessValue, "Business value"); score(input.feasibility, "Feasibility"); score(input.risk, "Risk"); return { code: input.code, ideaCode: input.idea.code, strategicFit: input.strategicFit, customerValue: input.customerValue, businessValue: input.businessValue, feasibility: input.feasibility, risk: input.risk, status: "candidate", ranked: false, decisionMade: false }; }
export function triageIdea(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; outcome: IdeaDispositionCandidate; missingContextReferences?: readonly string[] }): IdeaTriage { permit(input.permission); code(input.code, "Idea triage code"); return { code: input.code, ideaCode: input.idea.code, outcome: input.outcome, missingContextReferences: refs(input.missingContextReferences ?? [], "Missing context references"), status: "review_required", dispositionApplied: false, notificationSent: false }; }
export function createIdeaPack(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; ownerModuleReferences: readonly string[]; safetyGateReferences?: readonly string[] }): IdeaPack { permit(input.permission); code(input.code, "Idea pack code"); return { code: input.code, ideaCode: input.idea.code, domain: input.idea.domain, ownerModuleReferences: refs(input.ownerModuleReferences, "Owner module references", true), safetyGateReferences: refs(input.safetyGateReferences ?? [], "Safety gate references"), status: "draft", handoffExecuted: false }; }
export function requestIdeaParking(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; parkingLotReference: string; reasonReference: string }): IdeaParkingRequest { permit(input.permission); code(input.code, "Idea parking request code"); ref(input.parkingLotReference, "Parking lot reference"); ref(input.reasonReference, "Parking reason reference"); return { code: input.code, ideaCode: input.idea.code, parkingLotReference: input.parkingLotReference, reasonReference: input.reasonReference, status: "review_required", parkingWriteExecuted: false }; }
export function requestIdeaPromotion(input: { permission: IdeasPermission; code: string; idea: IdeaRecord; destination: IdeaPromotionDestination; destinationReference: string; precheckReferences: readonly string[] }): IdeaPromotionRequest { permit(input.permission); code(input.code, "Idea promotion request code"); ref(input.destinationReference, "Promotion destination reference"); return { code: input.code, ideaCode: input.idea.code, destination: input.destination, destinationReference: input.destinationReference, precheckReferences: refs(input.precheckReferences, "Promotion precheck references", true), status: "review_required", destinationWriteExecuted: false, outcomeKnown: false }; }
export function evaluateIdeaReadiness(input: { idea: IdeaRecord; triage: IdeaTriage }): IdeaReadinessResult { const reasons=["ideas_runtime_disabled", "human_triage_required", "evidence_unverified", "score_not_ranked", "promotion_not_authorized"]; if(input.idea.code!==input.triage.ideaCode) reasons.push("triage_idea_mismatch"); return { ideaCode: input.idea.code, ready: false, status: "not_ready", reasons }; }