import { assertExternalActionDisabled, assessOfferDisplay, configureIntegrationMode, createAdvertiser, createAffiliateLink, createAiDraft, createCommissionCandidate, createConversion, createDisabledJourney, createOffer, createRuleSnapshot, createTerms, recordDecision, type CcbAdvertiser, type CcbOffer, type CcbOfferSource, type CcbRuleSnapshot } from "@atlas/creditcardbroker";
import { describe, expect, it } from "vitest";
const now = "2026-08-25T00:00:00.000Z";
const rule: CcbRuleSnapshot = { id: "rule", sourceUrl: "https://rules.example/program", sourceType: "program_rules", ruleVersion: "v1", retrievedAt: now, effectiveAt: null, contentHash: "a".repeat(64), status: "reviewed", reviewedBy: "reviewer", reviewedAt: now };
const advertiser: CcbAdvertiser = { id: "advertiser", networkProviderId: "ccb-network", externalAdvertiserId: "issuer", legalName: "Example Issuer", displayName: "Example Issuer", providerType: "issuer", status: "active", source: { id: "advertiser-source", sourceType: "partner_export", sourceUrl: null, contentHash: "b".repeat(64), retrievedAt: now, verification: "reviewed" } };
const source: CcbOfferSource = { id: "source", externalOfferId: "offer", externalCategory: "consumer", advertiserId: advertiser.id, sourceMethod: "manual_verified_entry", sourcePayloadReference: "payload-ref", rawPayloadHash: "c".repeat(64), sourceVersion: "v1", retrievedAt: now, status: "validated" };
const offer: CcbOffer = { id: "offer", externalOfferId: source.externalOfferId, advertiserId: advertiser.id, sourceId: source.id, sourceVersion: source.sourceVersion, productFamily: "consumer_credit_card", status: "active", freshnessStatus: "current", createdAt: now, updatedAt: now };
describe("M039 CreditCardBroker", () => {
  it("versions partner rules and cannot activate a provider", () => { expect(createRuleSnapshot(rule, [])).toEqual(rule); expect(() => createRuleSnapshot(rule, [rule])).toThrow("already exists"); expect(() => configureIntegrationMode({ id: "mode", mode: "api", authorizationStatus: "approved", approvedDomains: ["sgsllc.com"], approvedSurfaces: ["marketplace"], capabilities: ["offers_read"], sourceRuleSnapshotId: rule.id, status: "configured" })).toThrow("cannot enable"); });
  it("separates the advertiser and validates source-controlled offers", () => { expect(createAdvertiser(advertiser)).toEqual(advertiser); expect(createOffer(offer, source, advertiser)).toEqual(offer); });
  it("rejects PII in affiliate URLs and blocks external action", () => { expect(() => createAffiliateLink({ id: "link", offerId: offer.id, externalTrackingUrl: "https://partner.example/apply?email=client@example.com", destinationHost: "partner.example", trackingParameterNames: ["email"], sourceId: source.id, sourceVersion: source.sourceVersion, status: "verified" }, ["partner.example"])).toThrow("PII"); expect(() => assertExternalActionDisabled()).toThrow("disabled"); });
  it("blocks a complete display while provider activation is off", () => { const result = assessOfferDisplay({ offer, terms: createTerms({ id: "terms", offerId: offer.id, sourceId: source.id, sourceVersion: source.sourceVersion, values: { annual_fee: null }, importantTermsUrl: null, retrievedAt: now, status: "current" }), link: { id: "safe-link", offerId: offer.id, externalTrackingUrl: "https://partner.example/apply?subid=opaque", destinationHost: "partner.example", trackingParameterNames: ["subid"], sourceId: source.id, sourceVersion: source.sourceVersion, status: "verified" }, disclosurePresent: true, sourceCurrent: true, contentReviewed: true }); expect(result.status).toBe("provider_disabled"); expect(result.ctaEnabled).toBe(false); });
  it("preserves unknown outcomes and cannot earn an unverified commission", () => { const journey = createDisabledJourney({ id: "journey", marketplaceJourneyId: "marketplace-journey", offerId: offer.id, displayId: "display", clientReference: null, consentId: null, createdAt: now, updatedAt: now }, []); const decision = recordDecision({ id: "decision", journeyId: journey.id, sourceId: source.id, status: "reported_approved", verification: "unverified", receivedAt: now }); const definition = { id: "definition", code: "approved" as const, version: 1, qualifyingEvidenceTypes: ["signed_statement"] as const, status: "active" as const, sourceId: source.id }; const conversion = createConversion({ id: "conversion", journeyId: journey.id, definitionId: definition.id, externalEventReference: "event", status: "reported", evidenceType: null, evidenceReference: null, receivedAt: now }, definition, []); const commission = createCommissionCandidate({ id: "commission", conversionId: conversion.id, ruleId: "commission-rule", status: "candidate", amountCents: 1000, currency: "USD", qualifyingEvidenceReference: null, createdAt: now, updatedAt: now }, { id: "commission-rule", partnerAccountId: "account", version: 1, conversionDefinitionId: definition.id, calculationType: "external_statement_only", amountCents: null, basisPoints: null, currency: "USD", status: "active", sourceId: source.id }, conversion); expect(journey.status).toBe("provider_disabled"); expect(decision.status).toBe("unknown"); expect(conversion.status).toBe("unknown"); expect(commission).toMatchObject({ status: "candidate", amountCents: null }); });
  it("requires grounded reviewed AI content", () => { expect(() => createAiDraft({ id: "ai", offerId: offer.id, sourceIds: [source.id], claims: [{ text: "Guaranteed approval", sourceId: source.id }], content: "Guaranteed approval", createdAt: now }, [source.id])).toThrow("approval"); expect(createAiDraft({ id: "safe-ai", offerId: offer.id, sourceIds: [source.id], claims: [{ text: "Terms are from the partner.", sourceId: source.id }], content: "Terms are from the partner.", createdAt: now }, [source.id]).status).toBe("requires_review"); });
});