import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const ideaRecords = pgTable("m102_idea_records", { id: uuid("id").primaryKey(), code: text("code").notNull().unique(), systemReference: text("system_reference").notNull(), version: integer("version").notNull(), sourceType: text("source_type").notNull(), domain: text("domain").notNull(), scope: text("scope").notNull(), title: text("title").notNull(), problemReference: text("problem_reference").notNull(), opportunityReference: text("opportunity_reference").notNull(), status: text("status").notNull(), promoted: boolean("promoted").notNull().default(false), parked: boolean("parked").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaAssumptions = pgTable("m102_idea_assumptions", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), assumptionType: text("assumption_type").notNull(), reference: text("reference").notNull(), status: text("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaEvidenceLinks = pgTable("m102_idea_evidence_links", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), evidenceType: text("evidence_type").notNull(), reference: text("reference").notNull(), verificationStatus: text("verification_status").notNull(), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaScorecards = pgTable("m102_idea_scorecards", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), strategicFit: integer("strategic_fit").notNull(), customerValue: integer("customer_value").notNull(), businessValue: integer("business_value").notNull(), feasibility: integer("feasibility").notNull(), risk: integer("risk").notNull(), status: text("status").notNull(), ranked: boolean("ranked").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaTriageRecords = pgTable("m102_idea_triage_records", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), outcome: text("outcome").notNull(), missingContextReferences: text("missing_context_references").array().notNull(), status: text("status").notNull(), dispositionApplied: boolean("disposition_applied").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaPacks = pgTable("m102_idea_packs", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), domain: text("domain").notNull(), ownerModuleReferences: text("owner_module_references").array().notNull(), safetyGateReferences: text("safety_gate_references").array().notNull(), status: text("status").notNull(), handoffExecuted: boolean("handoff_executed").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaParkingRequests = pgTable("m102_idea_parking_requests", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), parkingLotReference: text("parking_lot_reference").notNull(), reasonReference: text("reason_reference").notNull(), status: text("status").notNull(), parkingWriteExecuted: boolean("parking_write_executed").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const ideaPromotionRequests = pgTable("m102_idea_promotion_requests", { id: uuid("id").primaryKey(), ideaId: uuid("idea_id").notNull().references(() => ideaRecords.id), code: text("code").notNull().unique(), destination: text("destination").notNull(), destinationReference: text("destination_reference").notNull(), precheckReferences: text("precheck_references").array().notNull(), status: text("status").notNull(), destinationWriteExecuted: boolean("destination_write_executed").notNull().default(false), outcomeKnown: boolean("outcome_known").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });