import { boolean, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const parkingItems = pgTable("m103_parking_items", { id: uuid("id").primaryKey(), code: text("code").notNull().unique(), systemReference: text("system_reference").notNull(), sourceReference: text("source_reference").notNull(), version: integer("version").notNull(), scope: text("scope").notNull(), status: text("status").notNull(), sourceSynchronized: boolean("source_synchronized").notNull().default(false), reactivated: boolean("reactivated").notNull().default(false), promoted: boolean("promoted").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingContextSnapshots = pgTable("m103_parking_context_snapshots", { id: uuid("id").primaryKey(), parkingItemId: uuid("parking_item_id").notNull().references(() => parkingItems.id), code: text("code").notNull().unique(), evidenceReferences: text("evidence_references").array().notNull(), assumptionReferences: text("assumption_references").array().notNull(), dependencyReferences: text("dependency_references").array().notNull(), riskReferences: text("risk_references").array().notNull(), status: text("status").notNull(), contextRefreshed: boolean("context_refreshed").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingDecisions = pgTable("m103_parking_decisions", { id: uuid("id").primaryKey(), parkingItemId: uuid("parking_item_id").notNull().references(() => parkingItems.id), code: text("code").notNull().unique(), reason: text("reason").notNull(), reasonReference: text("reason_reference").notNull(), status: text("status").notNull(), decisionApplied: boolean("decision_applied").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingRevisitPolicies = pgTable("m103_parking_revisit_policies", { id: uuid("id").primaryKey(), parkingItemId: uuid("parking_item_id").notNull().references(() => parkingItems.id), code: text("code").notNull().unique(), triggerTypes: text("trigger_types").array().notNull(), triggerReferences: text("trigger_references").array().notNull(), status: text("status").notNull(), schedulerRegistered: boolean("scheduler_registered").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingRequests = pgTable("m103_parking_requests", { id: uuid("id").primaryKey(), code: text("code").notNull().unique(), sourceReference: text("source_reference").notNull(), reasonReference: text("reason_reference").notNull(), status: text("status").notNull(), targetItemCreated: boolean("target_item_created").notNull().default(false), sourceUpdated: boolean("source_updated").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingRevisitRequests = pgTable("m103_parking_revisit_requests", { id: uuid("id").primaryKey(), parkingItemId: uuid("parking_item_id").notNull().references(() => parkingItems.id), code: text("code").notNull().unique(), triggerType: text("trigger_type").notNull(), triggerReference: text("trigger_reference").notNull(), status: text("status").notNull(), contextRefreshStarted: boolean("context_refresh_started").notNull().default(false), reviewStarted: boolean("review_started").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingReactivationRequests = pgTable("m103_parking_reactivation_requests", { id: uuid("id").primaryKey(), parkingItemId: uuid("parking_item_id").notNull().references(() => parkingItems.id), code: text("code").notNull().unique(), destination: text("destination").notNull(), destinationReference: text("destination_reference").notNull(), precheckReferences: text("precheck_references").array().notNull(), status: text("status").notNull(), destinationWriteExecuted: boolean("destination_write_executed").notNull().default(false), outcomeKnown: boolean("outcome_known").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });
export const parkingDispositionRequests = pgTable("m103_parking_disposition_requests", { id: uuid("id").primaryKey(), parkingItemId: uuid("parking_item_id").notNull().references(() => parkingItems.id), code: text("code").notNull().unique(), action: text("action").notNull(), targetReference: text("target_reference").notNull(), status: text("status").notNull(), dispositionApplied: boolean("disposition_applied").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull() });