import type { AuthSql, AuthTransactionSql } from "./auth-repository.ts";
const q = <T>(tx: AuthTransactionSql, sql: string, params: readonly unknown[] = []) => tx.unsafe<T>(sql, params);
export class PostgresAuthSessionInvitationRepository {
  constructor(private readonly sql: AuthSql) {}
  async revokeCurrent(handleDigest: string, now: Date) { const rows = await this.sql.begin((tx) => q<readonly { id: string }[]>(tx, `update auth_sessions set state='revoked', revoked_at=$2, updated_at=$2 where handle_digest=$1 and state='active' returning id`, [handleDigest, now])); return Boolean(rows[0]); }
  async revokeOthers(handleDigest: string, now: Date) { const rows = await this.sql.begin((tx) => q<readonly { id: string }[]>(tx, `with current_session as (select id, account_id from auth_sessions where handle_digest=$1 and state='active' for update) update auth_sessions set state='revoked', revoked_at=$2, updated_at=$2 where account_id=(select account_id from current_session) and id<>(select id from current_session) and state='active' returning id`, [handleDigest, now])); return rows.length >= 0; }
  async consumeInvitation(input: { id: string; proofDigest: string; identityEvidenceId: string; contactId: string; scope: string; now: Date }) { const rows = await this.sql.begin((tx) => q<readonly { id: string }[]>(tx, `update auth_invitations set state='accepted', accepted_at=$6, updated_at=$6 where id=$1 and proof_digest=$2 and contact_id=$3 and scope=$4 and identity_evidence_id=$5 and state='issued' and expires_at>$6 returning id`, [input.id,input.proofDigest,input.contactId,input.scope,input.identityEvidenceId,input.now])); return rows[0] ? { kind: "consumed" as const } : { kind: "manual_review" as const }; }
  async issueInvitation(input: { id: string; proofDigest: string; contactId: string; scope: string; inviterAccountId: string; expiresAt: Date; now: Date }) { await this.sql.begin((tx) => q(tx, `insert into auth_durable_invitations (id, proof_digest, contact_id, scope, inviter_account_id, state, expires_at, created_at, updated_at) values ($1,$2,$3,$4,$5,'issued',$6,$7,$7)`, [input.id,input.proofDigest,input.contactId,input.scope,input.inviterAccountId,input.expiresAt,input.now])); }
  async acceptDurableInvitation(input: { id: string; proofDigest: string; identityEvidenceId: string; contactId: string; scope: string; now: Date }) { const rows = await this.sql.begin((tx) => q<readonly { id: string }[]>(tx, `update auth_durable_invitations set state='accepted', identity_evidence_id=$3, accepted_at=$6, updated_at=$6 where id=$1 and proof_digest=$2 and contact_id=$4 and scope=$5 and state='issued' and expires_at>$6 returning id`, [input.id,input.proofDigest,input.identityEvidenceId,input.contactId,input.scope,input.now])); return rows[0] ? { kind: "consumed" as const } : { kind: "manual_review" as const }; }
}
