import type { AuthSql, AuthTransactionSql } from "./auth-repository.ts";
const query = <T>(transaction: AuthTransactionSql, statement: string, parameters: readonly unknown[]) => transaction.unsafe<T>(statement, parameters);

export class PostgresEmailAuthRepository {
  constructor(private readonly sql: AuthSql) {}
  async consumeProviderToken(input: { tokenDigest: string; purpose: "verification" | "recovery"; now: Date }): Promise<boolean> { const rows = await this.sql.begin((transaction) => query<readonly { consumed: boolean }[]>(transaction, "select atlas_auth_consume_email_provider_token($1,$2,$3) consumed", [input.tokenDigest,input.purpose,input.now])); return rows[0]?.consumed === true; }
  async establishSession(input: { accountId: string; externalIdentityId: string; sessionId: string; familyId: string; subject: string; handleDigest: string; providerTokenCiphertext: string; idleExpiresAt: Date; absoluteExpiresAt: Date; now: Date }): Promise<{ kind: "established"; accountId: string } | { kind: "denied" }> { const rows = await this.sql.begin((transaction) => query<readonly { account_id: string | null }[]>(transaction, "select atlas_auth_establish_email_session($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) account_id", [input.accountId,input.externalIdentityId,input.sessionId,input.familyId,input.subject,input.handleDigest,input.providerTokenCiphertext,input.idleExpiresAt,input.absoluteExpiresAt,input.now])); return rows[0]?.account_id ? { kind: "established", accountId: rows[0].account_id } : { kind: "denied" }; }
  async loadProviderToken(input: { handleDigest: string; now: Date }): Promise<string | undefined> { const rows = await this.sql.begin((transaction) => query<readonly { ciphertext: string }[]>(transaction, "select ciphertext from atlas_auth_load_email_provider_token($1,$2)", [input.handleDigest,input.now])); return rows[0]?.ciphertext; }
  async clearProviderToken(input: { handleDigest: string; now: Date }): Promise<void> { await this.sql.begin((transaction) => query(transaction, "select atlas_auth_clear_email_provider_token($1,$2)", [input.handleDigest,input.now])); }
}
