export const TECHNICAL_ROADMAP_MODULE = "M100" as const;
export const TECHNICAL_ROADMAP_PERMISSIONS = ["technical_roadmap.create", "technical_roadmap.version.manage", "technical_roadmap.initiative.manage", "technical_roadmap.risk.manage", "technical_roadmap.decision_gate.manage", "technical_roadmap.review.request", "technical_roadmap.runtime.activate"] as const;
export type TechnicalRoadmapPermission = (typeof TECHNICAL_ROADMAP_PERMISSIONS)[number];
export const TECHNICAL_ROADMAP_RUNTIME = { sourceDiscovery: false, progressAggregation: false, automaticPrioritization: false, workCreation: false, providerActivation: false, deploymentOrchestration: false, telemetryQueries: false, changeExecution: false } as const;
export type TechnicalRoadmapHorizon = "foundation" | "enablement" | "scale" | "resilience" | "future";
export type TechnicalRiskSeverity = "low" | "medium" | "high" | "critical" | "unknown";

export interface TechnicalRoadmap { readonly module: typeof TECHNICAL_ROADMAP_MODULE; readonly code: string; readonly title: string; readonly status: "draft"; readonly active: false; readonly automaticExecutionEnabled: false; readonly businessAuthority: false; }
export interface TechnicalRoadmapVersion { readonly code: string; readonly roadmapCode: string; readonly versionNumber: number; readonly changeSummary: string; readonly status: "draft"; readonly immutable: false; readonly approved: false; }
export interface TechnicalInitiative { readonly code: string; readonly roadmapVersionCode: string; readonly horizon: TechnicalRoadmapHorizon; readonly ownerModuleReferences: readonly string[]; readonly dependencyReferences: readonly string[]; readonly evidenceReferences: readonly string[]; readonly status: "planned"; readonly progress: "not_started"; readonly providerActivated: false; readonly deploymentStarted: false; }
export interface TechnicalMilestone { readonly code: string; readonly initiativeCode: string; readonly definitionOfDoneReferences: readonly string[]; readonly evidenceReferences: readonly string[]; readonly status: "not_started"; readonly complete: false; readonly approved: false; }
export interface TechnicalRisk { readonly code: string; readonly roadmapVersionCode: string; readonly severity: TechnicalRiskSeverity; readonly category: "security" | "reliability" | "capacity" | "cost" | "vendor_lock_in" | "delivery" | "unknown"; readonly evidenceReferences: readonly string[]; readonly status: "open"; readonly accepted: false; readonly mitigationExecuted: false; }
export interface TechnicalDecisionGate { readonly code: string; readonly roadmapVersionCode: string; readonly decisionReference: string; readonly affectedInitiativeReferences: readonly string[]; readonly status: "pending_product_owner_decision"; readonly decisionRecorded: false; readonly executionAuthorized: false; }
export interface TechnicalReviewRequest { readonly code: string; readonly roadmapVersionCode: string; readonly evidenceReferences: readonly string[]; readonly status: "review_required"; readonly reviewPerformed: false; readonly priorityChanged: false; }

function permit(value: TechnicalRoadmapPermission): void { if (!TECHNICAL_ROADMAP_PERMISSIONS.includes(value)) throw new Error("Unsupported technical roadmap permission."); }
function code(value: string, field: string): void { if (!/^[A-Z][A-Z0-9_:-]{2,127}$/u.test(value)) throw new Error(`${field} must be a stable safe identifier.`); }
function ref(value: string, field: string): void { if (!/^[A-Za-z0-9][A-Za-z0-9._:/@-]{2,255}$/u.test(value)) throw new Error(`${field} must be a safe reference.`); }
function refs(values: readonly string[], field: string, required = false): readonly string[] { if (required && !values.length) throw new Error(`${field} requires at least one reference.`); for (const value of values) ref(value, field); return [...new Set(values)]; }
function safeText(value: string, field: string): void { if (/(-----BEGIN|authorization:|bearer\s|password\s*=|api[_-]?key\s*=|token\s*=|chain[\s-]?of[\s-]?thought)/iu.test(value)) throw new Error(`${field} cannot contain credentials or private reasoning.`); }

export function createTechnicalRoadmap(input: { permission: TechnicalRoadmapPermission; code: string; title: string }): TechnicalRoadmap { permit(input.permission); code(input.code, "Technical roadmap code"); safeText(input.title, "Technical roadmap title"); return { module: TECHNICAL_ROADMAP_MODULE, code: input.code, title: input.title, status: "draft", active: false, automaticExecutionEnabled: false, businessAuthority: false }; }
export function createTechnicalRoadmapVersion(input: { permission: TechnicalRoadmapPermission; code: string; roadmap: TechnicalRoadmap; versionNumber: number; changeSummary: string }): TechnicalRoadmapVersion { permit(input.permission); code(input.code, "Technical roadmap version code"); if (!Number.isSafeInteger(input.versionNumber) || input.versionNumber < 1) throw new Error("Roadmap version must be a positive integer."); safeText(input.changeSummary, "Technical roadmap change summary"); return { code: input.code, roadmapCode: input.roadmap.code, versionNumber: input.versionNumber, changeSummary: input.changeSummary, status: "draft", immutable: false, approved: false }; }
export function createTechnicalInitiative(input: { permission: TechnicalRoadmapPermission; code: string; version: TechnicalRoadmapVersion; horizon: TechnicalRoadmapHorizon; ownerModuleReferences: readonly string[]; dependencyReferences?: readonly string[]; evidenceReferences?: readonly string[] }): TechnicalInitiative { permit(input.permission); code(input.code, "Technical initiative code"); return { code: input.code, roadmapVersionCode: input.version.code, horizon: input.horizon, ownerModuleReferences: refs(input.ownerModuleReferences, "Owner module references", true), dependencyReferences: refs(input.dependencyReferences ?? [], "Dependency references"), evidenceReferences: refs(input.evidenceReferences ?? [], "Evidence references"), status: "planned", progress: "not_started", providerActivated: false, deploymentStarted: false }; }
export function createTechnicalMilestone(input: { permission: TechnicalRoadmapPermission; code: string; initiative: TechnicalInitiative; definitionOfDoneReferences: readonly string[]; evidenceReferences?: readonly string[] }): TechnicalMilestone { permit(input.permission); code(input.code, "Technical milestone code"); return { code: input.code, initiativeCode: input.initiative.code, definitionOfDoneReferences: refs(input.definitionOfDoneReferences, "Definition of done references", true), evidenceReferences: refs(input.evidenceReferences ?? [], "Evidence references"), status: "not_started", complete: false, approved: false }; }
export function createTechnicalRisk(input: { permission: TechnicalRoadmapPermission; code: string; version: TechnicalRoadmapVersion; severity: TechnicalRiskSeverity; category: TechnicalRisk["category"]; evidenceReferences?: readonly string[] }): TechnicalRisk { permit(input.permission); code(input.code, "Technical risk code"); return { code: input.code, roadmapVersionCode: input.version.code, severity: input.severity, category: input.category, evidenceReferences: refs(input.evidenceReferences ?? [], "Risk evidence references"), status: "open", accepted: false, mitigationExecuted: false }; }
export function createTechnicalDecisionGate(input: { permission: TechnicalRoadmapPermission; code: string; version: TechnicalRoadmapVersion; decisionReference: string; affectedInitiativeReferences: readonly string[] }): TechnicalDecisionGate { permit(input.permission); code(input.code, "Technical decision gate code"); ref(input.decisionReference, "Decision reference"); return { code: input.code, roadmapVersionCode: input.version.code, decisionReference: input.decisionReference, affectedInitiativeReferences: refs(input.affectedInitiativeReferences, "Affected initiative references", true), status: "pending_product_owner_decision", decisionRecorded: false, executionAuthorized: false }; }
export function requestTechnicalReview(input: { permission: TechnicalRoadmapPermission; code: string; version: TechnicalRoadmapVersion; evidenceReferences?: readonly string[] }): TechnicalReviewRequest { permit(input.permission); code(input.code, "Technical review request code"); return { code: input.code, roadmapVersionCode: input.version.code, evidenceReferences: refs(input.evidenceReferences ?? [], "Review evidence references"), status: "review_required", reviewPerformed: false, priorityChanged: false }; }