import type { DashboardRouteKey } from "@atlas/dashboard";
import { dashboardCopy, type DashboardLocale } from "@atlas/i18n";
import type { ReactNode } from "react";
export const DASHBOARD_ROUTE_HREFS: Readonly<Record<DashboardRouteKey, string>> = Object.freeze({ home: "/client", services: "/client/services", status: "/client/status", documents: "/client/documents", appointments: "/client/appointments", messages: "/client/messages", payments: "/client/payments", help: "/client/help", settings: "/client/settings/account", security: "/client/security", support: "/client/help" });
const desktopRoutes = ["home", "services", "status", "documents", "appointments", "messages", "payments", "help", "settings"] as const;
const mobilePrimary = ["home", "services", "documents"] as const;
const mobileMore = ["status", "appointments", "messages", "payments", "help", "settings"] as const;
const routeIcon: Readonly<Record<(typeof desktopRoutes)[number], string>> = Object.freeze({ home: "H", services: "S", status: "E", documents: "D", appointments: "C", messages: "M", payments: "P", help: "?", settings: "A" });
export function ClientPortalShell({ locale, activeRoute, contextType = "personal", contextControl, utility, children }: Readonly<{ locale: DashboardLocale; activeRoute: DashboardRouteKey; contextType?: "personal" | "organization"; contextControl?: ReactNode; utility?: ReactNode; children: ReactNode }>) { const copy = dashboardCopy[locale]; const link = (route: (typeof desktopRoutes)[number]) => <a key={route} href={DASHBOARD_ROUTE_HREFS[route]} aria-current={activeRoute === route ? "page" : undefined}><span aria-hidden="true">{routeIcon[route]}</span>{copy.nav[route]}</a>; return <div className="client-portal"><a className="skip-link" href="#client-main">{copy.skipToContent}</a><aside className="portal-rail"><a className="portal-brand" href="/client" aria-label={`${copy.brand} ${copy.portal}`}><span aria-hidden="true">SG</span><strong>{copy.brand}</strong><small>{copy.portal}</small></a><nav aria-label={copy.navigation} className="portal-nav">{desktopRoutes.map(link)}</nav><div className="portal-support-link"><a href={DASHBOARD_ROUTE_HREFS.support}>{copy.actions.support}</a></div></aside><div className="portal-stage"><header className="portal-topbar"><div><span>{copy.context.label}</span><strong>{contextType === "organization" ? copy.context.organization : copy.context.personal}</strong></div>{contextControl}<div className="portal-utility">{utility}</div></header><main id="client-main" className="portal-main">{children}</main></div><nav aria-label={copy.mobileNavigation} className="portal-mobile-nav">{mobilePrimary.map(link)}<details className="portal-mobile-more"><summary><span aria-hidden="true">+</span>{copy.nav.more}</summary><div>{mobileMore.map(link)}</div></details></nav></div>; }
