import type { DashboardDto, DashboardRouteKey } from "@atlas/dashboard";
import { dashboardCopy, type DashboardLocale } from "@atlas/i18n";
import { ClientPortalShell } from "./ClientPortalShell.tsx";
import { DashboardSkeleton, DashboardStateNotice } from "./DashboardStates.tsx";
import { PriorityActionCard } from "./PriorityActionCard.tsx";
import { AppointmentsWidget, ContextSwitchControl, DocumentsWidget, HelpWidget, MessagesWidget, NotificationsWidget, PaymentsWidget, ServicesWidget, SupportWidget, TasksWidget } from "./DashboardWidgets.tsx";
export function DashboardView({ dto, csrfToken }: Readonly<{ dto: DashboardDto; csrfToken?: string }>) { const copy = dashboardCopy[dto.locale]; const contextControl = csrfToken && dto.context.options.length > 1 ? <ContextSwitchControl locale={dto.locale} csrfToken={csrfToken} activeContext={dto.context.selectedOpaqueRef} options={dto.context.options} /> : undefined; const greeting = dto.greetingName ? copy.greetingNamed.replace("{name}", dto.greetingName) : copy.greeting; return <ClientPortalShell locale={dto.locale} activeRoute="home" contextType={dto.context.type} contextControl={contextControl}>{dto.security.state === "unavailable" || dto.security.state === "stale" ? <div className="dashboard-critical"><DashboardStateNotice locale={dto.locale} state={dto.security.state} /></div> : null}{dto.importantAlerts.state === "fresh" && dto.importantAlerts.data?.length ? <section className="dashboard-alerts" aria-label={copy.widgets.notifications}><NotificationsWidget locale={dto.locale} section={dto.importantAlerts} /></section> : null}<header className="dashboard-welcome"><p>{copy.portal}</p><h1>{greeting}</h1><span>{copy.intro}</span></header><PriorityActionCard locale={dto.locale} priority={dto.priority} /><div className="dashboard-grid"><ServicesWidget locale={dto.locale} section={dto.services} /><TasksWidget locale={dto.locale} section={dto.tasks} /><DocumentsWidget locale={dto.locale} section={dto.documents} /><AppointmentsWidget locale={dto.locale} section={dto.appointments} /><PaymentsWidget locale={dto.locale} section={dto.payments} /><MessagesWidget locale={dto.locale} section={dto.messages} /><NotificationsWidget locale={dto.locale} section={dto.notifications} /><HelpWidget locale={dto.locale} section={dto.help} /><SupportWidget locale={dto.locale} /></div></ClientPortalShell>; }
export function DashboardErrorView({ locale, onRetry }: Readonly<{ locale: DashboardLocale; onRetry?: () => void }>) { const copy = dashboardCopy[locale]; return <ClientPortalShell locale={locale} activeRoute="home"><section className="dashboard-page-error"><DashboardStateNotice locale={locale} state="error" /><p>{copy.pageError}</p>{onRetry ? <button type="button" onClick={onRetry}>{copy.actions.refresh}</button> : <a href="/client">{copy.actions.refresh}</a>}</section></ClientPortalShell>; }
export function ProviderDisabledPortalPage({ locale, route }: Readonly<{ locale: DashboardLocale; route: DashboardRouteKey }>) { const copy = dashboardCopy[locale]; return <ClientPortalShell locale={locale} activeRoute={route}><section className="dashboard-page-error"><DashboardStateNotice locale={locale} state="unavailable" /><h1>{copy.destination.unavailableTitle}</h1><p>{copy.destination.unavailableBody}</p><a href="/client">{copy.destination.back}</a></section></ClientPortalShell>; }
export function DashboardLoadingView({ locale }: Readonly<{ locale: DashboardLocale }>) { return <ClientPortalShell locale={locale} activeRoute="home"><div className="dashboard-loading"><DashboardSkeleton locale={locale} rows={2} /><DashboardSkeleton locale={locale} rows={4} /><DashboardSkeleton locale={locale} rows={3} /></div></ClientPortalShell>; }
