import { sanitizeDashboardDtoForSerialization, type DashboardDto } from "@atlas/dashboard";
import { recordDashboardEvent, type DashboardEventName } from "@atlas/observability";
import type { DashboardHttpDependencies } from "./configured-runtime.ts";
import type { DashboardRateAction } from "./dashboard-admission.ts";
import { DASHBOARD_CONTEXT_COOKIE, DASHBOARD_CSRF_COOKIE, DASHBOARD_SESSION_COOKIE, createDashboardContextCookie, readDashboardCookie } from "./auth-context.ts";
import { resolveDashboardLocale } from "./locale.ts";

type DashboardHttpRateAction = Extract<
  DashboardRateAction,
  "dashboard_get" | "dashboard_context" | "dashboard_analytics" | "dashboard_ssr"
>;
const PRIVATE_HEADERS = Object.freeze({ "cache-control": "private, no-store, max-age=0", pragma: "no-cache", vary: "Cookie", "content-security-policy": "default-src 'none'; frame-ancestors 'none'", "referrer-policy": "no-referrer", "x-content-type-options": "nosniff" });
function json(status: number, body: Readonly<Record<string, unknown>>, headers?: HeadersInit): Response { const serialized = status === 200 && "priority" in body ? sanitizeDashboardDtoForSerialization(body as DashboardDto) : body; return Response.json(serialized, { status, headers: { ...PRIVATE_HEADERS, ...headers } }); }
function empty(status: number, headers?: HeadersInit): Response { return new Response(null, { status, headers: { ...PRIVATE_HEADERS, ...headers } }); }
function locale(request: Request, dependencies: DashboardHttpDependencies) { return resolveDashboardLocale(readDashboardCookie(request, "atlas_locale"), dependencies.defaultLocale); }
export async function dashboardGet(request: Request, provided?: DashboardHttpDependencies): Promise<Response> { const dependencies = await resolveDependencies(provided); const sessionHandle = readDashboardCookie(request, DASHBOARD_SESSION_COOKIE); if (!sessionHandle) return json(401, { kind: "denied" }); if (hasRequestBody(request) || !await admitted(dependencies, "dashboard_get", request)) return empty(hasRequestBody(request) ? 413 : 429); const requestedContext = readDashboardCookie(request, DASHBOARD_CONTEXT_COOKIE); let result: Awaited<ReturnType<DashboardHttpDependencies["query"]>>; try { result = await dependencies.query({ sessionHandle, ...(requestedContext === undefined ? {} : { requestedContext }), locale: locale(request, dependencies) }); } catch { return json(409, { kind: "retry_required" }); } if (result.kind === "ok") return json(200, result.dto); if (result.kind === "retry_required") return json(409, { kind: "retry_required" }); return json(403, { kind: "denied" }); }
async function contextCommand(contentType: string, text: string): Promise<Readonly<{ context: string; csrf?: string; json: boolean }> | undefined> { try { if (contentType === "application/json") { const body: unknown = JSON.parse(text); if (!body || typeof body !== "object" || Array.isArray(body)) return undefined; const record = body as Record<string, unknown>; if (Object.keys(record).length !== 1 || typeof record.context !== "string") return undefined; return validContext(record.context) ? { context: record.context, json: true } : undefined; } if (contentType === "application/x-www-form-urlencoded") { const form = new URLSearchParams(text); const keys = [...new Set(form.keys())]; if (keys.length !== 2 || !keys.includes("context") || !keys.includes("csrf") || form.getAll("context").length !== 1 || form.getAll("csrf").length !== 1) return undefined; const context = form.get("context") ?? ""; const csrf = form.get("csrf") ?? ""; return validContext(context) && csrf.length > 0 && csrf.length <= 256 ? { context, csrf, json: false } : undefined; } return undefined; } catch { return undefined; } }
const validContext = (value: string): boolean => value.length > 0 && value.length <= 256 && !/[\r\n;]/u.test(value);
export async function dashboardContextPost(request: Request, provided?: DashboardHttpDependencies): Promise<Response> { const dependencies = await resolveDependencies(provided); const requestOrigin = new URL(request.url).origin; if (request.method !== "POST" || !dependencies.canonicalOrigin || requestOrigin !== dependencies.canonicalOrigin || request.headers.get("origin") !== dependencies.canonicalOrigin) return json(403, { kind: "denied" }); const sessionHandle = readDashboardCookie(request, DASHBOARD_SESSION_COOKIE); if (!sessionHandle || !await admitted(dependencies, "dashboard_context", request)) return empty(sessionHandle ? 429 : 403); const contentType = mediaType(request); if (contentType !== "application/json" && contentType !== "application/x-www-form-urlencoded") return empty(415); const body = await readBoundedBody(request, 1024); if (body.kind !== "ok") return empty(body.kind === "too_large" ? 413 : 400); const command = await contextCommand(contentType, body.text); if (!command) return json(400, { kind: "invalid_request" }); const csrfCookie = readDashboardCookie(request, DASHBOARD_CSRF_COOKIE); const csrfRequest = request.headers.get("x-atlas-csrf") ?? command.csrf ?? ""; if (!csrfCookie || csrfCookie !== csrfRequest || !dependencies.verifyCsrf(sessionHandle, csrfRequest)) return json(403, { kind: "denied" }); const result = await dependencies.selectContext({ sessionHandle, requestedContext: command.context }); if (result.kind !== "selected") return json(403, { kind: "denied" }); const refreshed = await dependencies.query({ sessionHandle, requestedContext: result.contextHandle, locale: locale(request, dependencies) }); if (refreshed.kind !== "ok") return json(409, { kind: "retry_required" }); const cookie = createDashboardContextCookie(result.contextHandle); await dependencies.emitAnalytics?.(recordDashboardEvent("client_dashboard_context_result", { locale: refreshed.dto.locale, resultCode: "selected" })); return command.json ? json(200, refreshed.dto, { "set-cookie": cookie }) : empty(303, { location: "/client", "set-cookie": cookie }); }
export async function dashboardAnalyticsPost(request: Request, provided?: DashboardHttpDependencies): Promise<Response> { const dependencies = await resolveDependencies(provided); const origin = new URL(request.url).origin; if (request.method !== "POST" || !dependencies.canonicalOrigin || origin !== dependencies.canonicalOrigin || request.headers.get("origin") !== dependencies.canonicalOrigin) return empty(403); const sessionHandle = readDashboardCookie(request, DASHBOARD_SESSION_COOKIE); const csrfCookie = readDashboardCookie(request, DASHBOARD_CSRF_COOKIE); const csrf = request.headers.get("x-atlas-csrf") ?? ""; if (!sessionHandle || !csrfCookie || csrf !== csrfCookie || !dependencies.verifyCsrf(sessionHandle, csrf)) return empty(403); if (!await admitted(dependencies, "dashboard_analytics", request)) return empty(429); if (mediaType(request) !== "application/json") return empty(415); const payload = await readBoundedBody(request, 2048); if (payload.kind !== "ok") return empty(payload.kind === "too_large" ? 413 : 400); try { const body = JSON.parse(payload.text) as { event?: unknown; properties?: unknown }; if (typeof body.event !== "string" || body.event.length > 80 || !body.properties || typeof body.properties !== "object" || Array.isArray(body.properties) || Object.keys(body.properties).length > 8) return empty(400); const authorization = await dependencies.query({ sessionHandle, ...(readDashboardCookie(request, DASHBOARD_CONTEXT_COOKIE) ? { requestedContext: readDashboardCookie(request, DASHBOARD_CONTEXT_COOKIE) } : {}), locale: locale(request, dependencies) }); if (authorization.kind !== "ok") return empty(403); const event = recordDashboardEvent(body.event as DashboardEventName, body.properties as Record<string, unknown>); await dependencies.emitAnalytics?.(event); return empty(202); } catch { return empty(400); } }

async function resolveDependencies(provided?: DashboardHttpDependencies): Promise<DashboardHttpDependencies> { return provided ?? (await import("./configured-runtime.ts")).createConfiguredDashboardRuntime(); }
async function admitted(dependencies: DashboardHttpDependencies, action: DashboardHttpRateAction, request: Request): Promise<boolean> { if (!dependencies.admit) return false; try { return await dependencies.admit(action, request) === "accepted"; } catch { return false; } }
function mediaType(request: Request): string { return (request.headers.get("content-type") ?? "").split(";", 1)[0]!.trim().toLowerCase(); }
function hasRequestBody(request: Request): boolean { const length = request.headers.get("content-length"); return request.body !== null || (length !== null && length !== "0"); }
async function readBoundedBody(request: Request, maximumBytes: number): Promise<Readonly<{ kind: "ok"; text: string }> | Readonly<{ kind: "too_large" | "invalid" }>> { const declared = request.headers.get("content-length"); if (declared !== null && (!/^\d{1,10}$/u.test(declared) || Number(declared) > maximumBytes)) return { kind: /^\d{1,10}$/u.test(declared) ? "too_large" : "invalid" }; if (!request.body) return { kind: "ok", text: "" }; const reader = request.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { for (;;) { const chunk = await reader.read(); if (chunk.done) break; total += chunk.value.byteLength; if (total > maximumBytes) { await reader.cancel(); return { kind: "too_large" }; } chunks.push(chunk.value); } const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } return { kind: "ok", text: new TextDecoder("utf-8", { fatal: true }).decode(bytes) }; } catch { return { kind: "invalid" }; } }
